/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-30 05:21:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kovidRMS.form.LoginForm;
import com.kovidRMS.daoInf.LoginDAOInf;
import com.kovidRMS.daoImpl.LoginDAOImpl;
import java.util.*;

public final class addUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.24.1.jar", Long.valueOf(1722313424386L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/KovidRMS/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SkoolUp/WEB-INF/lib/struts2-core-2.3.24.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1442915484000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.kovidRMS.daoImpl.LoginDAOImpl");
    _jspx_imports_classes.add("com.kovidRMS.form.LoginForm");
    _jspx_imports_classes.add("com.kovidRMS.daoInf.LoginDAOInf");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005factionerror_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005felse;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005frequired_005fonclick_005fname_005flist_005fheaderValue_005fheaderKey_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ffile_0026_005frequired_005fname_005fclass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005factionerror_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005felse = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005frequired_005fonclick_005fname_005flist_005fheaderValue_005fheaderKey_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ffile_0026_005frequired_005fname_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005factionerror_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005felse.release();
    _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005frequired_005fonclick_005fname_005flist_005fheaderValue_005fheaderKey_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005ffile_0026_005frequired_005fname_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE html>\r\n<html class=\"no-js\"> \r\n<head>\r\n\r\n	");

		LoginForm form = (LoginForm) session.getAttribute("USER");
		
		LoginDAOInf daoInf = new LoginDAOImpl();
	
		HashMap<Integer, String> LibraryList = daoInf.retrieveLibraryList(form.getOrganizationID());
	
      out.write("\r\n	\r\n	<title>");
 if(form.getMedium().equals("mr")){ 
      out.write("युझर नोंदवा  ");
}else{ 
      out.write(" Register User - SkoolUp ");
} 
      out.write("</title>\r\n\r\n<!-- Favicon -->\r\n  <link rel=\"shortcut icon\" href=\"images/favicon.jpg\">\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"viewport\" content=\"width=device-width\">\r\n  <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700\">\r\n  <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Oswald:400,300,700\">\r\n  <link rel=\"stylesheet\" href=\"font-awesome/css/font-awesome.min.css\">\r\n  <link rel=\"stylesheet\" href=\"./js/libs/css/ui-lightness/jquery-ui-1.9.2.custom.min.css\">\r\n  <link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\r\n   \r\n\r\n  <!-- Plugin CSS -->\r\n  <link rel=\"stylesheet\" href=\"./js/plugins/morris/morris.css\">\r\n  <link rel=\"stylesheet\" href=\"./js/plugins/icheck/skins/minimal/blue.css\">\r\n  <link rel=\"stylesheet\" href=\"./js/plugins/select2/select2.css\">\r\n  <link rel=\"stylesheet\" href=\"./js/plugins/fullcalendar/fullcalendar.css\">\r\n\r\n  <!-- App CSS -->\r\n  <link rel=\"stylesheet\" href=\"./css/target-admin.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/custom.css\">\r\n\r\n  <script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\"></script>\r\n \r\n<script type=\"text/javascript\">\r\n	$(document).ready(function(){\r\n		$('#administrationLiID').addClass(\"active\");\r\n		//alert(\"hiii\");	\r\n	});\r\n</script>\r\n\r\n<style type=\"text/css\">\r\n\r\n	ul.actionMessage{\r\n            list-style:none;\r\n            font-family: \"Helvetica Neue\", Roboto, Arial, \"Droid Sans\", sans-serif;\r\n        }\r\n        \r\n        ul.errorMessage{\r\n            list-style:none;\r\n            font-family: \"Helvetica Neue\", Roboto, Arial, \"Droid Sans\", sans-serif;\r\n        }\r\n       \r\n        /* Chrome, Safari, Edge, Opera */\r\n	input::-webkit-outer-spin-button,\r\n	input::-webkit-inner-spin-button {\r\n	  -webkit-appearance: none;\r\n	  margin: 0;\r\n	}\r\n	\r\n	/* Firefox */\r\n	input[type=number] {\r\n	  -moz-appearance: textfield;\r\n	}\r\n\r\n    .fixed-header{\r\n        position: fixed;\r\n        top: 43px;\r\n        z-index:1;\r\n        width: 100%;\r\n       	height: 107px;\r\n");
      out.write("    }\r\n    .fixed-navbar{\r\n        position: fixed;\r\n        \r\n        width: 100%;\r\n    }\r\n    \r\n    .loadingImage{\r\n        	position: absolute;\r\n          	left: 50%;\r\n           	top: 25%;\r\n         	margin-left: -50px; /*half the image width*/\r\n          	margin-top: 10%; /*half the image height*/\r\n          	color: black;\r\n           	z-index: 1;\r\n            display: none;\r\n    	} \r\n  \r\n</style>\r\n\r\n<script type=\"text/javascript\">\r\n    jQuery(document).ready(function($) {\r\n        $(\".scroll\").click(function(event){     \r\n            event.preventDefault();\r\n            $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n        });\r\n    });\r\n</script>\r\n\r\n <script type=\"text/javascript\">\r\n      function windowOpen(){\r\n    	  $('html, body').animate({\r\n		        scrollTop: $('body').offset().top\r\n		    }, 1000);\r\n			\r\n			$('body').css('background', '#FCFAF5');\r\n			$(\".container\").css(\"opacity\",\"0.2\");\r\n			$(\"#loader\").show();\r\n			$(\"body\").find(\"button\").attr(\"disabled\",\"disabled\"); //To disable My appo, view appo, search patient, add new pat buttons\r\n");
      out.write("			\r\n    	  document.location=\"welcome.jsp\";\r\n      }\r\n      \r\n      function windowOpen1(){\r\n			$('html, body').animate({\r\n		        scrollTop: $('body').offset().top\r\n		    }, 1000);\r\n			\r\n			$('body').css('background', '#FCFAF5');\r\n			$(\".container\").css(\"opacity\",\"0.2\");\r\n			$(\"#loader\").show();\r\n			$(\"body\").find(\"button\").attr(\"disabled\",\"disabled\"); //To disable My appo, view appo, search patient, add new pat buttons\r\n	\r\n          document.location=\"addUser.jsp\";\r\n        }\r\n      \r\n      function submitForm(subID){\r\n    	  	$('html, body').animate({\r\n		        scrollTop: $('body').offset().top\r\n		    }, 1000);\r\n			\r\n			$('body').css('background', '#FCFAF5');\r\n			$(\".container\").css(\"opacity\",\"0.2\");\r\n			$(\"#loader\").show();\r\n			$(\"body\").find(\"button\").attr(\"disabled\",\"disabled\"); //To disable My appo, view appo, search patient, add new pat buttons\r\n	\r\n	    	$(\"#loadStudentFOrm\").attr(\"action\",\"AddUser\");\r\n		 	$(\"#loadStudentFOrm\").submit(); \r\n		  	  \r\n	 	 	 $(\"#\"+subID).attr(\"disabled\", \"disabled\");\r\n");
      out.write("	 	 	 \r\n	 	 	 $(\"html, body\").animate({ scrollTop: 0 }, \"fast\");\r\n	    		$(\".loadingImage\").show();\r\n	    		$(\".container\").css(\"opacity\",\"0.1\");\r\n	    		$(\".navbar\").css(\"opacity\",\"0.1\");\r\n	    		return true;\r\n	   }\r\n      \r\n      function libraryShow(role) {\r\n		if(role == \"librarian\"){\r\n			$(\"#LibraryDivID\").show();\r\n			$(\"#libraryID\").attr(\"required\", true);\r\n			 \r\n		}else{\r\n			$(\"#libraryID\").val(\"\");\r\n			$(\"#LibraryDivID\").hide();\r\n			$(\"#libraryID\").removeAttr(\"required\", false);\r\n		}\r\n	}\r\n      \r\n    </script>\r\n\r\n</head>\r\n\r\n<body>\r\n\r\n<img src=\"images/Preloader_2.gif\" alt=\"Loading Icon\" class = \"loadingImage\" id=\"loader\">\r\n\r\n<!-- icluding top menu bar -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topMenu.jsp", out, false);
      out.write("\r\n\r\n<div class=\"container\">\r\n\r\n  <div class=\"content\">\r\n\r\n    <div class=\"content-container\" style=\"z-index: 0;\">\r\n\r\n       <div class=\"content-header\">\r\n       \r\n		<h2 class=\"content-header-title\">");
 if(form.getMedium().equals("mr")){ 
      out.write(" युझर नोंदवा  ");
}else{ 
      out.write(" Register User");
} 
      out.write("</h2>\r\n        <ol class=\"breadcrumb\">\r\n          <li><a onclick=\"windowOpen();\">");
 if(form.getMedium().equals("mr")){ 
      out.write(" मुख्यपृष्ठ ");
}else{ 
      out.write(" Home ");
} 
      out.write("</a></li>\r\n          <li class=\"active\">");
 if(form.getMedium().equals("mr")){ 
      out.write(" युझर नोंदवा  ");
}else{ 
      out.write(" Register User ");
} 
      out.write("</li>\r\n        </ol>\r\n\r\n      </div> <!-- /.content-header -->\r\n\r\n       <div class=\"row\">\r\n        <div class=\"col-sm-3\"></div>\r\n        <div class=\"col-sm-6\">\r\n\r\n          <div class=\"portlet\">\r\n\r\n            <div class=\"portlet-header\">\r\n\r\n              <h3>\r\n                <i class=\"fa fa-tasks\"></i>\r\n              	");
 if(form.getMedium().equals("mr")){ 
      out.write(" युझर तपशील  ");
 }else{ 
      out.write(" User Details ");
 } 
      out.write("\r\n              </h3>\r\n\r\n            </div> <!-- /.portlet-header -->\r\n\r\n            <div class=\"portlet-content\">\r\n			\r\n			<div>\r\n		        ");
      if (_jspx_meth_s_005fif_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_s_005felse_005f0(_jspx_page_context))
        return;
      out.write("\r\n		    </div>\r\n			\r\n              <form id=\"loadStudentFOrm\" action=\"AddUser\" method=\"POST\" data-validate=\"parsley\" enctype=\"multipart/form-data\" onsubmit=\"submitForm('submitID');\" class=\"form parsley-form\">\r\n 			\r\n 			");
 if(form.getMedium().equals("mr")){ 
      out.write("\r\n 			\r\n 				<div class=\"form-group\">\r\n                  <label for=\"name\">नाव<span class=\"required\">*</span></label>\r\n                  <div>\r\n                  <input type=\"text\" id=\"name\" style=\"width: 33%; display: inline-block;\" placeholder=\"पहिले नाव\" required=\"required\"  name=\"firstName\" class=\"form-control\" >\r\n                  <input type=\"text\" id=\"name\" style=\"width: 31%;display: inline-block;\" placeholder=\"मधले नाव\" name=\"middleName\" class=\"form-control\" >\r\n                  <input type=\"text\" id=\"name\" style=\"width: 33%;display: inline-block;\" placeholder=\"आडनाव\" required=\"required\" name=\"lastName\" class=\"form-control\" >\r\n                  </div>\r\n                </div>\r\n\r\n             	<div class=\"form-group\">\r\n                  <label for=\"name\">ई - मेल आयडी</label>\r\n                  <input type=\"email\" name=\"emailId\" placeholder=\"ईमेल आयडी\" class=\"form-control\" data-required=\"true\"  >\r\n                </div>\r\n\r\n                <div class=\"form-group\">\r\n                  <label for=\"name\">मोबाईल</label>\r\n");
      out.write("                  <input type=\"number\" name=\"mobile\" class=\"form-control\" placeholder=\"मोबाईल\" data-required=\"true\" onKeyPress=\"if(this.value.length==10) return false;\">\r\n                </div>\r\n\r\n                <div class=\"form-group\">\r\n                  <label for=\"name\">फोन</label>\r\n                  <input type=\"text\" name=\"phone\" class=\"form-control\" placeholder=\"फोन\" data-required=\"true\" onKeyPress=\"if(this.value.length==10) return false;\">\r\n                </div>\r\n	\r\n				<div class=\"form-group\">\r\n                  <label for=\"Username\">युझर नाव<span class=\"required\">*</span></label>\r\n                  <input type=\"text\" name=\"username\" required=\"required\" class=\"form-control\" placeholder=\"युझर नाव\" >\r\n                </div>\r\n				\r\n				<div class=\"form-group\">\r\n                  <label for=\"Password\">पासवर्ड <span class=\"required\">*</span></label>\r\n                  <input type=\"password\" name=\"password\" required=\"required\" class=\"form-control\" placeholder=\"पासवर्ड \" >\r\n                </div>\r\n                \r\n");
      out.write("				<div class=\"form-group\">\r\n                  <label for=\"textarea-input\">पत्ता</label>\r\n                  <textarea data-required=\"true\" data-minlength=\"5\" name=\"address\" id=\"textarea-input\" cols=\"10\" rows=\"2\" placeholder=\"पत्ता\" class=\"form-control\"></textarea>\r\n                </div>\r\n				\r\n                <div class=\"form-group\">\r\n                  <label for=\"name\">शहर</label>\r\n                  <input type=\"text\" name=\"city\" value=\"पुणे\" placeholder=\"शहर\" class=\"form-control\" >\r\n                </div>\r\n                <div class=\"form-group\">\r\n                  <label for=\"name\">राज्य</label>\r\n                  <input type=\"text\" name=\"state\" value=\"महाराष्ट्र\" placeholder=\"राज्य\" class=\"form-control\" >\r\n                </div>\r\n\r\n                <div class=\"form-group\">\r\n                  <label for=\"name\">देश</label>\r\n                  <input type=\"text\" name=\"country\" value=\"भारत\" readonly=\"readonly\" placeholder=\"देश\" class=\"form-control\" >\r\n                </div>\r\n\r\n                <div class=\"form-group\">\r\n");
      out.write("                  <label for=\"name\">पिन कोड</label>\r\n                  <input type=\"text\" name=\"pinCode\" placeholder=\"पिन कोड\" class=\"form-control\" >\r\n                </div>\r\n                \r\n                <div class=\"form-group\">\r\n                	<label for=\"name\">भूमिका<span class=\"required\">*</span></label>\r\n                    ");
 if(form.getRole().equals("superAdmin")){ 
      out.write("\r\n                    	");
      if (_jspx_meth_s_005fselect_005f0(_jspx_page_context))
        return;
      out.write("\r\n                   	");
 }else{ 
      out.write("\r\n                   		");
      if (_jspx_meth_s_005fselect_005f1(_jspx_page_context))
        return;
      out.write("\r\n                   	");
 } 
      out.write("\r\n                </div>\r\n                \r\n				<div class=\"form-group\" style=\"display: none;\" id=\"LibraryDivID\">\r\n                	<label for=\"name\">ग्रंथालय<span class=\"required\">*</span></label>\r\n                	\r\n                	<select id=\"libraryID\" class=\"form-control\" name=\"libraryID\" >\r\n					     <option value=\"-1\">ग्रंथालय निवडा</option>\r\n					     \r\n					");
 for(Integer libraryID : LibraryList.keySet()){ 
      out.write("\r\n						 \r\n						 <option value=\"");
      out.print(libraryID);
      out.write('"');
      out.write('>');
      out.print(LibraryList.get(libraryID));
      out.write("</option>\r\n					");
 } 
      out.write("\r\n				    </select> \r\n                 </div>\r\n                 \r\n				<div class=\"form-group\">\r\n                   <label for=\"Profile Pic\">प्रोफाइल फोटो अपलोड करा</label>\r\n                   <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n                       ");
      if (_jspx_meth_s_005ffile_005f0(_jspx_page_context))
        return;
      out.write("\r\n                   </div>\r\n                </div>\r\n                \r\n                <div class=\"form-group\">\r\n					<label for=\"Profile Pic\"> स्वाक्षरी अपलोड करा <span class=\"required\">*</span></label>\r\n					<div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n						");
      if (_jspx_meth_s_005ffile_005f1(_jspx_page_context))
        return;
      out.write("\r\n					</div>\r\n				</div>\r\n                      \r\n				 <div class=\"form-group\" align=\"center\">\r\n				  <button type=\"button\" onclick=\"windowOpen1();\" class=\"btn btn-default\">रद्द करा</button>\r\n                  <button type=\"submit\" class=\"btn btn-success\" id=\"submitID\" style=\"background: #ED6617;\">सेव करा</button>\r\n                 </div>\r\n 			\r\n 			");
 }else{ 
      out.write("\r\n 			\r\n               <div class=\"form-group\">\r\n                  <label for=\"name\">Name<span class=\"required\">*</span></label>\r\n                  <div>\r\n                  <input type=\"text\" id=\"name\" style=\"width: 33%; display: inline-block;\" placeholder=\"FirstName\" required=\"required\"  name=\"firstName\" class=\"form-control\" >\r\n                  <input type=\"text\" id=\"name\" style=\"width: 31%;display: inline-block;\" placeholder=\"MiddleName\" name=\"middleName\" class=\"form-control\" >\r\n                  <input type=\"text\" id=\"name\" style=\"width: 33%;display: inline-block;\" placeholder=\"LastName\" required=\"required\" name=\"lastName\" class=\"form-control\" >\r\n                  </div>\r\n                </div>\r\n\r\n             	<div class=\"form-group\">\r\n                  <label for=\"name\">Email ID</label>\r\n                  <input type=\"email\" name=\"emailId\" placeholder=\"Email Address\" class=\"form-control\" data-required=\"true\"  >\r\n                </div>\r\n\r\n                <div class=\"form-group\">\r\n                  <label for=\"name\">Mobile</label>\r\n");
      out.write("                  <input type=\"number\" name=\"mobile\" class=\"form-control\" placeholder=\"Mobile\" data-required=\"true\" onKeyPress=\"if(this.value.length==10) return false;\">\r\n                </div>\r\n\r\n                <div class=\"form-group\">\r\n                  <label for=\"name\">Phone</label>\r\n                  <input type=\"text\" name=\"phone\" class=\"form-control\" placeholder=\"Phone\" data-required=\"true\" onKeyPress=\"if(this.value.length==10) return false;\">\r\n                </div>\r\n	\r\n				<div class=\"form-group\">\r\n                  <label for=\"Username\">Username<span class=\"required\">*</span></label>\r\n                  <input type=\"text\" name=\"username\" required=\"required\" class=\"form-control\" placeholder=\"Username\" >\r\n                </div>\r\n				\r\n				<div class=\"form-group\">\r\n                  <label for=\"Password\">Password<span class=\"required\">*</span></label>\r\n                  <input type=\"password\" name=\"password\" required=\"required\" class=\"form-control\" placeholder=\"Password\" >\r\n                </div>\r\n                \r\n");
      out.write("				<div class=\"form-group\">\r\n                  <label for=\"textarea-input\">Address</label>\r\n                  <textarea data-required=\"true\" data-minlength=\"5\" name=\"address\" id=\"textarea-input\" cols=\"10\" rows=\"2\" placeholder=\"Address\" class=\"form-control\"></textarea>\r\n                </div>\r\n				\r\n                <div class=\"form-group\">\r\n                  <label for=\"name\">City</label>\r\n                  <input type=\"text\" name=\"city\" value=\"Pune\" placeholder=\"City\" class=\"form-control\" >\r\n                </div>\r\n                <div class=\"form-group\">\r\n                  <label for=\"name\">State</label>\r\n                  <input type=\"text\" name=\"state\" value=\"Maharashtra\" placeholder=\"State\" class=\"form-control\" >\r\n                </div>\r\n\r\n                <div class=\"form-group\">\r\n                  <label for=\"name\">Country</label>\r\n                  <input type=\"text\" name=\"country\" value=\"India\" readonly=\"readonly\" placeholder=\"Country\" class=\"form-control\" >\r\n                </div>\r\n\r\n                <div class=\"form-group\">\r\n");
      out.write("                  <label for=\"name\">PinCode</label>\r\n                  <input type=\"text\" name=\"pinCode\" placeholder=\"PIN\" class=\"form-control\" >\r\n                </div>\r\n                \r\n                <div class=\"form-group\">\r\n                	<label for=\"name\">Role<span class=\"required\">*</span></label>\r\n                    ");
 if(form.getRole().equals("superAdmin")){ 
      out.write("\r\n                    	");
      if (_jspx_meth_s_005fselect_005f2(_jspx_page_context))
        return;
      out.write("\r\n                   	");
 }else{ 
      out.write("\r\n                   		");
      if (_jspx_meth_s_005fselect_005f3(_jspx_page_context))
        return;
      out.write("\r\n                   	");
 } 
      out.write("\r\n                </div>\r\n				\r\n				 <div class=\"form-group\" style=\"display: none;\" id=\"LibraryDivID\">\r\n                	<label for=\"name\">Library<span class=\"required\">*</span></label>\r\n                	\r\n                	<select id=\"libraryID\" class=\"form-control\" name=\"libraryID\" >\r\n					     <option value=\"-1\">Select Library</option>\r\n					     \r\n					");
 for(Integer libraryID : LibraryList.keySet()){ 
      out.write("\r\n						 \r\n						 <option value=\"");
      out.print(libraryID);
      out.write('"');
      out.write('>');
      out.print(LibraryList.get(libraryID));
      out.write("</option>\r\n					");
 } 
      out.write("\r\n				    </select> \r\n                 </div>\r\n                \r\n				<div class=\"form-group\">\r\n                   <label for=\"Profile Pic\">Upload Profile Pic</label>\r\n                   <div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n                       ");
      if (_jspx_meth_s_005ffile_005f2(_jspx_page_context))
        return;
      out.write("\r\n                   </div>\r\n                </div>\r\n                \r\n                <div class=\"form-group\">\r\n					<label for=\"Profile Pic\">Upload Signature<span class=\"required\">*</span></label>\r\n					<div class=\"col-md-6 col-sm-6 col-xs-12\">\r\n						");
      if (_jspx_meth_s_005ffile_005f3(_jspx_page_context))
        return;
      out.write("\r\n					</div>\r\n				</div>\r\n                      \r\n				 <div class=\"form-group\" align=\"center\">\r\n				  <button type=\"button\" onclick=\"windowOpen1();\" class=\"btn btn-default\">Cancel</button>\r\n                  <button type=\"submit\" class=\"btn btn-success\" id=\"submitID\" style=\"background: #ED6617;\">Add User</button>\r\n                 </div>\r\n               \r\n            ");
 } 
      out.write("\r\n            \r\n               </form>\r\n\r\n            </div> <!-- /.portlet-content -->\r\n\r\n          </div> <!-- /.portlet -->\r\n          \r\n        </div> <!-- /.col -->\r\n\r\n      </div> <!-- /.row -->\r\n       \r\n    </div> <!-- /.content-container -->\r\n      \r\n  </div> <!-- /.content -->\r\n\r\n</div> <!-- /.container -->\r\n\r\n  <script src=\"./js/libs/jquery-ui-1.9.2.custom.min.js\"></script>\r\n  <script src=\"./js/libs/bootstrap.min.js\"></script>\r\n\r\n  <!-- Plugin JS -->\r\n  <script src=\"./js/plugins/icheck/jquery.icheck.js\"></script>\r\n  <script src=\"./js/plugins/select2/select2.js\"></script>\r\n  <script src=\"./js/libs/raphael-2.1.2.min.js\"></script>\r\n  <script src=\"./js/plugins/morris/morris.min.js\"></script>\r\n  <script src=\"./js/plugins/sparkline/jquery.sparkline.min.js\"></script>\r\n  <script src=\"./js/plugins/nicescroll/jquery.nicescroll.min.js\"></script>\r\n  <script src=\"./js/plugins/fullcalendar/fullcalendar.min.js\"></script>\r\n\r\n  <!-- App JS -->\r\n  <script src=\"./js/target-admin.js\"></script>\r\n  \r\n  <!-- Plugin JS -->\r\n");
      out.write("  <script src=\"./js/demos/dashboard.js\"></script>\r\n  <script src=\"./js/demos/calendar.js\"></script>\r\n  <script src=\"./js/demos/charts/morris/area.js\"></script>\r\n  <script src=\"./js/demos/charts/morris/donut.js\"></script>\r\n\r\n</body>\r\n</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f0_reused = false;
    try {
      _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f0.setParent(null);
      // /addUser.jsp(218,10) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f0.setTest("hasActionErrors()");
      int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f0);
        }
        do {
          out.write("\r\n					<center>\r\n						<font style=\"color: red; font-size:16px;\">");
          if (_jspx_meth_s_005factionerror_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
            return true;
          out.write("</font>\r\n					</center>\r\n				");
          int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      _jspx_th_s_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005factionerror_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:actionerror
    org.apache.struts2.views.jsp.ui.ActionErrorTag _jspx_th_s_005factionerror_005f0 = (org.apache.struts2.views.jsp.ui.ActionErrorTag) _005fjspx_005ftagPool_005fs_005factionerror_005fnobody.get(org.apache.struts2.views.jsp.ui.ActionErrorTag.class);
    boolean _jspx_th_s_005factionerror_005f0_reused = false;
    try {
      _jspx_th_s_005factionerror_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005factionerror_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
      int _jspx_eval_s_005factionerror_005f0 = _jspx_th_s_005factionerror_005f0.doStartTag();
      if (_jspx_th_s_005factionerror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005factionerror_005fnobody.reuse(_jspx_th_s_005factionerror_005f0);
      _jspx_th_s_005factionerror_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005factionerror_005f0, _jsp_getInstanceManager(), _jspx_th_s_005factionerror_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005felse_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:else
    org.apache.struts2.views.jsp.ElseTag _jspx_th_s_005felse_005f0 = (org.apache.struts2.views.jsp.ElseTag) _005fjspx_005ftagPool_005fs_005felse.get(org.apache.struts2.views.jsp.ElseTag.class);
    boolean _jspx_th_s_005felse_005f0_reused = false;
    try {
      _jspx_th_s_005felse_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005felse_005f0.setParent(null);
      int _jspx_eval_s_005felse_005f0 = _jspx_th_s_005felse_005f0.doStartTag();
      if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005felse_005f0);
        }
        do {
          out.write("\r\n					<center>\r\n						<font style=\"color: green;font-size:16px;\">");
          if (_jspx_meth_s_005factionmessage_005f0(_jspx_th_s_005felse_005f0, _jspx_page_context))
            return true;
          out.write("</font>\r\n					</center>\r\n				");
          int evalDoAfterBody = _jspx_th_s_005felse_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005felse_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005felse.reuse(_jspx_th_s_005felse_005f0);
      _jspx_th_s_005felse_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005felse_005f0, _jsp_getInstanceManager(), _jspx_th_s_005felse_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005factionmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005felse_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:actionmessage
    org.apache.struts2.views.jsp.ui.ActionMessageTag _jspx_th_s_005factionmessage_005f0 = (org.apache.struts2.views.jsp.ui.ActionMessageTag) _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.get(org.apache.struts2.views.jsp.ui.ActionMessageTag.class);
    boolean _jspx_th_s_005factionmessage_005f0_reused = false;
    try {
      _jspx_th_s_005factionmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005factionmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005felse_005f0);
      int _jspx_eval_s_005factionmessage_005f0 = _jspx_th_s_005factionmessage_005f0.doStartTag();
      if (_jspx_th_s_005factionmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.reuse(_jspx_th_s_005factionmessage_005f0);
      _jspx_th_s_005factionmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005factionmessage_005f0, _jsp_getInstanceManager(), _jspx_th_s_005factionmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fselect_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:select
    org.apache.struts2.views.jsp.ui.SelectTag _jspx_th_s_005fselect_005f0 = (org.apache.struts2.views.jsp.ui.SelectTag) _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005frequired_005fonclick_005fname_005flist_005fheaderValue_005fheaderKey_005fclass_005fnobody.get(org.apache.struts2.views.jsp.ui.SelectTag.class);
    boolean _jspx_th_s_005fselect_005f0_reused = false;
    try {
      _jspx_th_s_005fselect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fselect_005f0.setParent(null);
      // /addUser.jsp(294,21) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setCssClass("form-control");
      // /addUser.jsp(294,21) name = list type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setList("#{'administrator':'प्रशासक','teacher':'शिक्षक','officeAdmin':'कार्यालय प्रशासन', 'librarian':'ग्रंथपाल', 'NonTeaching':'शिक्षकेत्तर ', 'superAdmin':'सुपर अ‍ॅडमीन'}");
      // /addUser.jsp(294,21) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setValue("");
      // /addUser.jsp(294,21) name = headerKey type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setHeaderKey("-1");
      // /addUser.jsp(294,21) null
      _jspx_th_s_005fselect_005f0.setDynamicAttribute(null, "required", "required");
      // /addUser.jsp(294,21) name = headerValue type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setHeaderValue("भूमिका निवडा");
      // /addUser.jsp(294,21) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setName("role");
      // /addUser.jsp(294,21) name = onclick type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setOnclick("libraryShow(this.value);");
      int _jspx_eval_s_005fselect_005f0 = _jspx_th_s_005fselect_005f0.doStartTag();
      if (_jspx_th_s_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005frequired_005fonclick_005fname_005flist_005fheaderValue_005fheaderKey_005fclass_005fnobody.reuse(_jspx_th_s_005fselect_005f0);
      _jspx_th_s_005fselect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fselect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fselect_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:select
    org.apache.struts2.views.jsp.ui.SelectTag _jspx_th_s_005fselect_005f1 = (org.apache.struts2.views.jsp.ui.SelectTag) _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005frequired_005fonclick_005fname_005flist_005fheaderValue_005fheaderKey_005fclass_005fnobody.get(org.apache.struts2.views.jsp.ui.SelectTag.class);
    boolean _jspx_th_s_005fselect_005f1_reused = false;
    try {
      _jspx_th_s_005fselect_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fselect_005f1.setParent(null);
      // /addUser.jsp(297,21) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setCssClass("form-control");
      // /addUser.jsp(297,21) name = list type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setList("#{'administrator':'प्रशासक','teacher':'शिक्षक','officeAdmin':'कार्यालय प्रशासन', 'librarian':'ग्रंथपाल', 'NonTeaching':'शिक्षकेत्तर '}");
      // /addUser.jsp(297,21) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setValue("");
      // /addUser.jsp(297,21) name = headerKey type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setHeaderKey("-1");
      // /addUser.jsp(297,21) null
      _jspx_th_s_005fselect_005f1.setDynamicAttribute(null, "required", "required");
      // /addUser.jsp(297,21) name = headerValue type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setHeaderValue("भूमिका निवडा");
      // /addUser.jsp(297,21) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setName("role");
      // /addUser.jsp(297,21) name = onclick type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setOnclick("libraryShow(this.value);");
      int _jspx_eval_s_005fselect_005f1 = _jspx_th_s_005fselect_005f1.doStartTag();
      if (_jspx_th_s_005fselect_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005frequired_005fonclick_005fname_005flist_005fheaderValue_005fheaderKey_005fclass_005fnobody.reuse(_jspx_th_s_005fselect_005f1);
      _jspx_th_s_005fselect_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fselect_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fselect_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ffile_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:file
    org.apache.struts2.views.jsp.ui.FileTag _jspx_th_s_005ffile_005f0 = (org.apache.struts2.views.jsp.ui.FileTag) _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fclass_005fnobody.get(org.apache.struts2.views.jsp.ui.FileTag.class);
    boolean _jspx_th_s_005ffile_005f0_reused = false;
    try {
      _jspx_th_s_005ffile_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005ffile_005f0.setParent(null);
      // /addUser.jsp(318,23) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ffile_005f0.setName("profilePic");
      // /addUser.jsp(318,23) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ffile_005f0.setCssClass("form-control");
      int _jspx_eval_s_005ffile_005f0 = _jspx_th_s_005ffile_005f0.doStartTag();
      if (_jspx_th_s_005ffile_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fclass_005fnobody.reuse(_jspx_th_s_005ffile_005f0);
      _jspx_th_s_005ffile_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ffile_005f0, _jsp_getInstanceManager(), _jspx_th_s_005ffile_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ffile_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:file
    org.apache.struts2.views.jsp.ui.FileTag _jspx_th_s_005ffile_005f1 = (org.apache.struts2.views.jsp.ui.FileTag) _005fjspx_005ftagPool_005fs_005ffile_0026_005frequired_005fname_005fclass_005fnobody.get(org.apache.struts2.views.jsp.ui.FileTag.class);
    boolean _jspx_th_s_005ffile_005f1_reused = false;
    try {
      _jspx_th_s_005ffile_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005ffile_005f1.setParent(null);
      // /addUser.jsp(325,6) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ffile_005f1.setName("signature");
      // /addUser.jsp(325,6) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ffile_005f1.setCssClass("form-control");
      // /addUser.jsp(325,6) null
      _jspx_th_s_005ffile_005f1.setDynamicAttribute(null, "required", "required");
      int _jspx_eval_s_005ffile_005f1 = _jspx_th_s_005ffile_005f1.doStartTag();
      if (_jspx_th_s_005ffile_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ffile_0026_005frequired_005fname_005fclass_005fnobody.reuse(_jspx_th_s_005ffile_005f1);
      _jspx_th_s_005ffile_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ffile_005f1, _jsp_getInstanceManager(), _jspx_th_s_005ffile_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fselect_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:select
    org.apache.struts2.views.jsp.ui.SelectTag _jspx_th_s_005fselect_005f2 = (org.apache.struts2.views.jsp.ui.SelectTag) _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005frequired_005fonclick_005fname_005flist_005fheaderValue_005fheaderKey_005fclass_005fnobody.get(org.apache.struts2.views.jsp.ui.SelectTag.class);
    boolean _jspx_th_s_005fselect_005f2_reused = false;
    try {
      _jspx_th_s_005fselect_005f2.setPageContext(_jspx_page_context);
      _jspx_th_s_005fselect_005f2.setParent(null);
      // /addUser.jsp(397,21) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f2.setCssClass("form-control");
      // /addUser.jsp(397,21) name = list type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f2.setList("#{'administrator':'Administrator','teacher':'Teacher','officeAdmin':'Office Admin', 'librarian':'Librarian', 'NonTeaching':'Non-Teaching', 'superAdmin':'Super Admin'}");
      // /addUser.jsp(397,21) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f2.setValue("");
      // /addUser.jsp(397,21) name = headerKey type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f2.setHeaderKey("");
      // /addUser.jsp(397,21) null
      _jspx_th_s_005fselect_005f2.setDynamicAttribute(null, "required", "required");
      // /addUser.jsp(397,21) name = headerValue type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f2.setHeaderValue("Select Role");
      // /addUser.jsp(397,21) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f2.setName("role");
      // /addUser.jsp(397,21) name = onclick type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f2.setOnclick("libraryShow(this.value);");
      int _jspx_eval_s_005fselect_005f2 = _jspx_th_s_005fselect_005f2.doStartTag();
      if (_jspx_th_s_005fselect_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005frequired_005fonclick_005fname_005flist_005fheaderValue_005fheaderKey_005fclass_005fnobody.reuse(_jspx_th_s_005fselect_005f2);
      _jspx_th_s_005fselect_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fselect_005f2, _jsp_getInstanceManager(), _jspx_th_s_005fselect_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fselect_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:select
    org.apache.struts2.views.jsp.ui.SelectTag _jspx_th_s_005fselect_005f3 = (org.apache.struts2.views.jsp.ui.SelectTag) _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005frequired_005fonclick_005fname_005flist_005fheaderValue_005fheaderKey_005fclass_005fnobody.get(org.apache.struts2.views.jsp.ui.SelectTag.class);
    boolean _jspx_th_s_005fselect_005f3_reused = false;
    try {
      _jspx_th_s_005fselect_005f3.setPageContext(_jspx_page_context);
      _jspx_th_s_005fselect_005f3.setParent(null);
      // /addUser.jsp(400,21) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f3.setCssClass("form-control");
      // /addUser.jsp(400,21) name = list type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f3.setList("#{'administrator':'Administrator','teacher':'Teacher', 'officeAdmin':'Office Admin', 'librarian':'Librarian', 'NonTeaching':'Non-Teaching'}");
      // /addUser.jsp(400,21) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f3.setValue("");
      // /addUser.jsp(400,21) name = headerKey type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f3.setHeaderKey("");
      // /addUser.jsp(400,21) null
      _jspx_th_s_005fselect_005f3.setDynamicAttribute(null, "required", "required");
      // /addUser.jsp(400,21) name = headerValue type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f3.setHeaderValue("Select Role");
      // /addUser.jsp(400,21) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f3.setName("role");
      // /addUser.jsp(400,21) name = onclick type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f3.setOnclick("libraryShow(this.value);");
      int _jspx_eval_s_005fselect_005f3 = _jspx_th_s_005fselect_005f3.doStartTag();
      if (_jspx_th_s_005fselect_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005frequired_005fonclick_005fname_005flist_005fheaderValue_005fheaderKey_005fclass_005fnobody.reuse(_jspx_th_s_005fselect_005f3);
      _jspx_th_s_005fselect_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fselect_005f3, _jsp_getInstanceManager(), _jspx_th_s_005fselect_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ffile_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:file
    org.apache.struts2.views.jsp.ui.FileTag _jspx_th_s_005ffile_005f2 = (org.apache.struts2.views.jsp.ui.FileTag) _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fclass_005fnobody.get(org.apache.struts2.views.jsp.ui.FileTag.class);
    boolean _jspx_th_s_005ffile_005f2_reused = false;
    try {
      _jspx_th_s_005ffile_005f2.setPageContext(_jspx_page_context);
      _jspx_th_s_005ffile_005f2.setParent(null);
      // /addUser.jsp(421,23) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ffile_005f2.setName("profilePic");
      // /addUser.jsp(421,23) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ffile_005f2.setCssClass("form-control");
      int _jspx_eval_s_005ffile_005f2 = _jspx_th_s_005ffile_005f2.doStartTag();
      if (_jspx_th_s_005ffile_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ffile_0026_005fname_005fclass_005fnobody.reuse(_jspx_th_s_005ffile_005f2);
      _jspx_th_s_005ffile_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ffile_005f2, _jsp_getInstanceManager(), _jspx_th_s_005ffile_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005ffile_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:file
    org.apache.struts2.views.jsp.ui.FileTag _jspx_th_s_005ffile_005f3 = (org.apache.struts2.views.jsp.ui.FileTag) _005fjspx_005ftagPool_005fs_005ffile_0026_005frequired_005fname_005fclass_005fnobody.get(org.apache.struts2.views.jsp.ui.FileTag.class);
    boolean _jspx_th_s_005ffile_005f3_reused = false;
    try {
      _jspx_th_s_005ffile_005f3.setPageContext(_jspx_page_context);
      _jspx_th_s_005ffile_005f3.setParent(null);
      // /addUser.jsp(428,6) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ffile_005f3.setName("signature");
      // /addUser.jsp(428,6) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005ffile_005f3.setCssClass("form-control");
      // /addUser.jsp(428,6) null
      _jspx_th_s_005ffile_005f3.setDynamicAttribute(null, "required", "required");
      int _jspx_eval_s_005ffile_005f3 = _jspx_th_s_005ffile_005f3.doStartTag();
      if (_jspx_th_s_005ffile_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005ffile_0026_005frequired_005fname_005fclass_005fnobody.reuse(_jspx_th_s_005ffile_005f3);
      _jspx_th_s_005ffile_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005ffile_005f3, _jsp_getInstanceManager(), _jspx_th_s_005ffile_005f3_reused);
    }
    return false;
  }
}
