/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-30 05:22:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javassist.expr.NewArray;
import com.kovidRMS.daoImpl.ConfigurationDAOImpl;
import com.kovidRMS.daoInf.ConfigurationDAOInf;
import com.kovidRMS.daoInf.LoginDAOInf;
import com.kovidRMS.daoImpl.LoginDAOImpl;
import java.util.HashMap;
import com.kovidRMS.daoInf.StuduntDAOInf;
import com.kovidRMS.daoImpl.StudentDAOImpl;
import com.kovidRMS.form.StudentForm;
import com.kovidRMS.form.ConfigurationForm;
import java.util.List;
import com.kovidRMS.form.LoginForm;

public final class studentAttendance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.24.1.jar", Long.valueOf(1722313424386L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/KovidRMS/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SkoolUp/WEB-INF/lib/struts2-core-2.3.24.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1442915484000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(12);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.kovidRMS.daoImpl.LoginDAOImpl");
    _jspx_imports_classes.add("com.kovidRMS.daoImpl.ConfigurationDAOImpl");
    _jspx_imports_classes.add("com.kovidRMS.form.LoginForm");
    _jspx_imports_classes.add("javassist.expr.NewArray");
    _jspx_imports_classes.add("com.kovidRMS.daoImpl.StudentDAOImpl");
    _jspx_imports_classes.add("com.kovidRMS.daoInf.ConfigurationDAOInf");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("com.kovidRMS.form.StudentForm");
    _jspx_imports_classes.add("com.kovidRMS.daoInf.LoginDAOInf");
    _jspx_imports_classes.add("com.kovidRMS.daoInf.StuduntDAOInf");
    _jspx_imports_classes.add("com.kovidRMS.form.ConfigurationForm");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005factionerror_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005felse;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fselect_0026_005fonchange_005fname_005flist_005fid_005fheaderValue_005fheaderKey_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fselect_0026_005fname_005flist_005fid_005fheaderValue_005fheaderKey_005fclass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005factionerror_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005felse = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fonchange_005fname_005flist_005fid_005fheaderValue_005fheaderKey_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fname_005flist_005fid_005fheaderValue_005fheaderKey_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005factionerror_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005felse.release();
    _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fonchange_005fname_005flist_005fid_005fheaderValue_005fheaderKey_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fname_005flist_005fid_005fheaderValue_005fheaderKey_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n     \r\n<!DOCTYPE html>\r\n<html class=\"no-js\"> \r\n<head>\r\n  <title>Student Attendance - SkoolUp</title>\r\n<!-- Favicon -->\r\n  <link rel=\"shortcut icon\" href=\"images/favicon.jpg\">\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"viewport\" content=\"width=device-width\">\r\n\r\n  <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700\">\r\n  <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Oswald:400,300,700\">\r\n  <link rel=\"stylesheet\" href=\"font-awesome/css/font-awesome.min.css\">\r\n  <link rel=\"stylesheet\" href=\"./js/libs/css/ui-lightness/jquery-ui-1.9.2.custom.min.css\">\r\n  <link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\r\n    <link rel=\"stylesheet\" href=\"./js/plugins/datepicker/datepicker.css\">\r\n   \r\n\r\n  <!-- Plugin CSS -->\r\n  <link rel=\"stylesheet\" href=\"./js/plugins/morris/morris.css\">\r\n  <link rel=\"stylesheet\" href=\"./js/plugins/icheck/skins/minimal/blue.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./js/plugins/select2/select2.css\">\r\n  <link rel=\"stylesheet\" href=\"./js/plugins/fullcalendar/fullcalendar.css\">\r\n\r\n  <!-- App CSS -->\r\n  <link rel=\"stylesheet\" href=\"./css/target-admin.css\">\r\n  <link rel=\"stylesheet\" href=\"./css/custom.css\">\r\n\r\n  <script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\">\r\n</script>\r\n\r\n  <script type=\"text/javascript\">\r\n  \r\n	$(document).ready(function(){\r\n		$('#studentLiID').addClass(\"active\");\r\n		//alert(\"hiii\");	\r\n	});\r\n	\r\n	jQuery(document).ready(function($) {\r\n        $(\".scroll\").click(function(event){     \r\n            event.preventDefault();\r\n            $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n        });\r\n    });\r\n</script>\r\n\r\n<style type=\"text/css\">\r\n	ul.actionMessage{\r\n            list-style:none;\r\n            font-family: \"Helvetica Neue\", Roboto, Arial, \"Droid Sans\", sans-serif;\r\n        }\r\n        \r\n        ul.errorMessage{\r\n            list-style:none;\r\n            font-family: \"Helvetica Neue\", Roboto, Arial, \"Droid Sans\", sans-serif;\r\n");
      out.write("        }\r\n</style>\r\n\r\n<style type=\"text/css\">\r\n    .fixed-header{\r\n        position: fixed;\r\n        top: 43px;\r\n        z-index:1;\r\n        width: 100%;\r\n       	height: 107px;\r\n    }\r\n    .fixed-navbar{\r\n        position: fixed;\r\n        \r\n        width: 100%;\r\n    }\r\n    \r\n     /* Chrome, Safari, Edge, Opera */\r\ninput::-webkit-outer-spin-button,\r\ninput::-webkit-inner-spin-button {\r\n  -webkit-appearance: none;\r\n  margin: 0;\r\n}\r\n\r\n/* Firefox */\r\ninput[type=number] {\r\n  -moz-appearance: textfield;\r\n}\r\n</style>\r\n\r\n	");

		LoginForm loginform = (LoginForm) session.getAttribute("USER");
		
		LoginDAOInf daoinf = new LoginDAOImpl();
		
		ConfigurationDAOInf configurationDAOInf = new ConfigurationDAOImpl();
    	
		int AcademicYearID = loginform.getAcademicYearID();
		
		String StandardName = daoinf.retrieveStandardName(loginform.getUserID(), AcademicYearID);
    	
    	int StandardID = daoinf.retrieveStandardID(loginform.getUserID(), AcademicYearID);
    	
		String DivisionName = daoinf.retrieveDivisionName(loginform.getUserID(), AcademicYearID);
		
    	int DivisionID = daoinf.retrieveDivisionID(loginform.getUserID(), AcademicYearID);
		
    	HashMap<Integer, String> StandardList = daoinf.getStandard(loginform.getOrganizationID());
    	
    	String workingDays = (String)(request.getAttribute("workingDays"));
    
      out.write("\r\n\r\n<script type=\"text/javascript\" src=\"//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit\"></script>\r\n<script type=\"text/javascript\">\r\n	\r\n	function googleTranslateElementInit() {\r\n		  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');\r\n	}\r\n	\r\n	function changeLanguageByButtonClick(language) {\r\n		setTimeout(function(){\r\n			var selectField = document.querySelector(\"#google_translate_element select\");\r\n			\r\n			  for(var i=0; i < selectField.children.length; i++){\r\n			    var option = selectField.children[i];\r\n			    // find desired langauge and change the former language of the hidden selection-field \r\n			    \r\n			    if(option.value==language){\r\n			       selectField.selectedIndex = i;\r\n			       // trigger change event afterwards to make google-lib translate this side\r\n			       selectField.dispatchEvent(new Event('change'));\r\n			       break;\r\n			    }\r\n			  }\r\n		},1000);\r\n	}\r\n</script>\r\n\r\n<style>\r\n	.goog-te-banner-frame,.custom-translate {\r\n	        display: none;\r\n");
      out.write("	}\r\n	\r\n	body {\r\n	        top: 0 !important;\r\n	    }\r\n	.goog-tooltip {\r\n	    display: none !important;\r\n	}\r\n	.goog-tooltip:hover {\r\n	    display: none !important;\r\n	}\r\n	.goog-text-highlight {\r\n	    background-color: transparent !important;\r\n	    border: none !important; \r\n	    box-shadow: none !important;\r\n	}\r\n\r\n</style>\r\n\r\n <script type=\"text/javascript\">\r\n\r\n	\r\n      function windowOpen(){\r\n        document.location=\"welcome.jsp\";\r\n      }\r\n      \r\n      function windowOpen1(){\r\n          document.location=\"RenderStudentAttendance\";\r\n        }\r\n      \r\n   \r\n      function checkStandard(term,month){\r\n  		\r\n  		if(term == \"-1\" ){\r\n  			alert(\"Please select term.\");\r\n  			return false;\r\n  		}else if(month == \"-1\" ){\r\n  			alert(\"Please select month.\");\r\n  			return false;\r\n  		}else{\r\n  			\r\n  			$(\"#loadStudentFOrm\").attr(\"action\",\"LoadStudentForAttendance\");\r\n  		    $(\"#loadStudentFOrm\").submit();\r\n  		    \r\n  		  $(\"html, body\").animate({ scrollTop: 0 }, \"fast\");\r\n  		$(\".loadingImage\").show();\r\n  		$(\".container\").css(\"opacity\",\"0.1\");\r\n");
      out.write("  		$(\".navbar\").css(\"opacity\",\"0.1\");\r\n  		return true;\r\n  		\r\n  		}\r\n  		\r\n      }\r\n  	\r\n      function checkStandard1(term,month){\r\n    \r\n   		$(\"#loadStudentFOrm\").attr(\"action\",\"StudentsAttendanceReportExcel\");\r\n	    $(\"#loadStudentFOrm\").submit();\r\n    \r\n      }\r\n      \r\n </script>\r\n	 \r\n	");

		List<StudentForm> studentsList = (List<StudentForm>) request.getAttribute("studentsList");
	
		List<StudentForm> NewStudentsList = (List<StudentForm>) request.getAttribute("NewStudentsList");
	
		String loadStudentSearch = (String) request.getAttribute("loadStudentSearch");
	
		if(loadStudentSearch == null || loadStudentSearch == ""){
			loadStudentSearch = "dummy";
		}
		
		String classTeacherCheck = (String) request.getAttribute("classTeacherCheck");
		
		if(classTeacherCheck == null || classTeacherCheck == ""){
			classTeacherCheck = "dummy";
		}
		
	
      out.write("\r\n\r\n<script type=\"text/javascript\">\r\n	\r\n	 var xmlhttp;\r\n		if (window.XMLHttpRequest) {\r\n			xmlhttp = new XMLHttpRequest();\r\n		} else {\r\n			xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n		}\r\n		\r\n	function retrieveDivision(standardID){\r\n		\r\n		if(standardID == \"-1\"){\r\n			alert(\"No standard is selected. Please select standard.\");\r\n			\r\n			var array_element = \"<select name='divisionID' id='' class='form-control'\"+\r\n			\"> <option value='-1'>Select Division</option></select>\";\r\n			\r\n			document.getElementById(\"stdDivID\").innerHTML = array_element;\r\n		\r\n		}else{\r\n			retrieveDivision1(standardID);\r\n		}\r\n		\r\n	}\r\n\r\n	function retrieveDivision1(standardID) {\r\n\r\n		xmlhttp.onreadystatechange = function() {\r\n			if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\r\n\r\n				var array = JSON.parse(xmlhttp.responseText);\r\n				\r\n					var array_element = \"<select name='divisionID' class='form-control'\"+\r\n					\"> <option value='-1'>Select Division</option>\";\r\n					\r\n					var check = 0;\r\n					/* For division */\r\n					for ( var i = 0; i < array.Release.length; i++) {\r\n");
      out.write("						\r\n						check = array.Release[i].check;\r\n\r\n						array_element += \"<option value='\"+array.Release[i].divisionID+\"'>\"+array.Release[i].division+\"</option>\";\r\n					}\r\n\r\n					array_element += \" </select>\";\r\n					\r\n					if(check == 0){\r\n						\r\n						alert(\"No division found\");\r\n						\r\n						var array_element = \"<select name='divisionID' id='' class='form-control'\"+\r\n						\"> <option value='-1'>Select Division</option></select>\";\r\n						\r\n						document.getElementById(\"stdDivID\").innerHTML = array_element;\r\n						\r\n					}else{\r\n						\r\n						document.getElementById(\"stdDivID\").innerHTML = array_element;	\r\n													\r\n					}\r\n			}return true;\r\n\r\n		};\r\n		xmlhttp.open(\"GET\", \"RetrieveDivisionListForStandard?standardID=\"\r\n				+ standardID, true);\r\n		xmlhttp.setRequestHeader(\"Content-type\", \"charset=UTF-8\");\r\n		xmlhttp.send();\r\n	}\r\n</script>\r\n\r\n<script type=\"text/javascript\">\r\n	\r\n	 var xmlhttp;\r\n		if (window.XMLHttpRequest) {\r\n			xmlhttp = new XMLHttpRequest();\r\n		} else {\r\n			xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("		}\r\n		\r\n	function retrieveworkingMonth(term, standardID){\r\n		\r\n		if(term == \"-1\"){\r\n			alert(\"No term is selected. Please select term.\");\r\n			\r\n			var array_element = \"<select name='workingMonth' id='' class='form-control'\"+\r\n			\"> <option value='-1'>Select Month</option></select>\";\r\n			\r\n			document.getElementById(\"monthID\").innerHTML = array_element;\r\n		\r\n		}else{\r\n			retrieveworkingMonth1(term, standardID);\r\n		}\r\n		\r\n	}\r\n\r\n	function retrieveworkingMonth1(term, standardID) {\r\n\r\n		xmlhttp.onreadystatechange = function() {\r\n			if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\r\n\r\n				var array = JSON.parse(xmlhttp.responseText);\r\n				\r\n					var array_element = \"<select name='workingMonth' class='form-control'\"+\r\n					\"> <option value='-1'>Select Month</option>\";\r\n					\r\n					var check = 0;\r\n					/* For division */\r\n					for ( var i = 0; i < array.Release.length; i++) {\r\n						\r\n						check = array.Release[i].check;\r\n\r\n						array_element += \"<option value='\"+array.Release[i].workingMonth+\"'>\"+array.Release[i].workingMonth+\"</option>\";\r\n");
      out.write("					}\r\n\r\n					array_element += \" </select>\";\r\n					\r\n					if(check == 0){\r\n						\r\n						alert(\"No workingMonth found\");\r\n						\r\n						var array_element = \"<select name='workingMonth' id='' class='form-control'\"+\r\n						\"> <option value='-1'>Select Month</option></select>\";\r\n						\r\n						document.getElementById(\"monthID\").innerHTML = array_element;\r\n						\r\n					}else{\r\n						\r\n						document.getElementById(\"monthID\").innerHTML = array_element;	\r\n													\r\n					}\r\n			}\r\n\r\n		};\r\n		xmlhttp.open(\"GET\", \"RetrieveworkingMonthForAttendance?term=\"\r\n				+ term + \"&standardID=\" + standardID, true);\r\n		xmlhttp.setRequestHeader(\"Content-type\", \"charset=UTF-8\");\r\n		xmlhttp.send();\r\n	}\r\n	\r\n	function submitForm(subID){\r\n  	  $(\"#loadStudentFOrm\").attr(\"action\",\"AddAttendance\");\r\n  	  $(\"#loadStudentFOrm\").submit();\r\n    \r\n  	 $(\"#\"+subID).attr(\"disabled\", \"disabled\");\r\n	\r\n  	$(\"html, body\").animate({ scrollTop: 0 }, \"fast\");\r\n	$(\".loadingImage\").show();\r\n	$(\".container\").css(\"opacity\",\"0.1\");\r\n	$(\".navbar\").css(\"opacity\",\"0.1\");\r\n");
      out.write("	return true;\r\n	\r\n	}\r\n</script>\r\n\r\n<script type=\"text/javascript\"> \r\n\r\n	function assignName(input, studentID, studHiddenID, check, WorkingDays, SpanID){\r\n		//alert(input.value);\r\n		var attendanceVal = $(\"#\"+input).val();\r\n		\r\n		if(check == \"Attendance\"){\r\n			\r\n			if(attendanceVal == \"\"){\r\n				\r\n				$(\"#\"+input).removeAttr(\"name\",\"daysPresentArr\");\r\n				\r\n				$(\"#\"+studHiddenID).removeAttr(\"name\", \"studID\");\r\n				\r\n			}else{\r\n				\r\n				if(attendanceVal <= WorkingDays){\r\n					\r\n					$(\"#\"+SpanID).html(\"\");\r\n					$(\"#\"+input).attr(\"name\",\"daysPresentArr\");\r\n					$(\"#\"+studHiddenID).attr(\"name\", \"studID\");\r\n					$(\"#submitID\").attr(\"disabled\", false);\r\n					\r\n				}else{\r\n					\r\n					$(\"#\"+SpanID).html(\"Value entered must be less than or equal to \"+WorkingDays);\r\n					//alert(\"Value entered must be less than or equal to \"+WorkingDays);\r\n					$(\"#submitID\").attr(\"disabled\", true);\r\n				}\r\n			}\r\n		}\r\n	}\r\n	\r\n	function assignNameNew(input, WorkingDays, SpanID){\r\n		//alert(input.value);\r\n		var attendanceVal = $(\"#\"+input).val();\r\n");
      out.write("		\r\n		if(attendanceVal <= WorkingDays){\r\n					\r\n			$(\"#\"+SpanID).html(\"\");\r\n			$(\"#submitID\").attr(\"disabled\", false);\r\n					\r\n		}else{\r\n					\r\n			$(\"#\"+SpanID).html(\"Value entered must be less than or equal to \"+WorkingDays);\r\n			$(\"#submitID\").attr(\"disabled\", true);\r\n		}\r\n	}\r\n	\r\n</script>	\r\n\r\n<style type=\"text/css\">\r\n    	.loadingImage{\r\n    		position: absolute;\r\n	        width: 100px; /*the image width*/\r\n	        height: 100px; /*the image height*/\r\n	        left: 50%;\r\n	        top: 50%;\r\n	        margin-left: -50px; /*half the image width*/\r\n	        margin-top: -50px; /*half the image height*/\r\n	        \r\n    	}\r\n   </style>\r\n   \r\n</head>\r\n\r\n<body onload=\"changeLanguageByButtonClick('");
      out.print(loginform.getMedium());
      out.write("');\">\r\n\r\n<img src=\"images/loading.gif\" alt=\"Loading...\" class=\"loadingImage\" style=\"z-index:1;display: none;\">\r\n<!-- icluding top menu bar -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topMenu.jsp", out, false);
      out.write("\r\n\r\n<div id=\"google_translate_element\" style=\"display:none\"></div>\r\n\r\n<div class=\"container\">\r\n\r\n  <div class=\"content\">\r\n\r\n    <div class=\"content-container\" style=\"z-index: 0;\">\r\n\r\n      \r\n\r\n      <div class=\"content-header\">\r\n        <h2 class=\"content-header-title\">Student Attendance</h2>\r\n        <ol class=\"breadcrumb\">\r\n          <li><a onclick=\"windowOpen();\">Home</a></li>\r\n          <li class=\"active\">Student Attendance</li>\r\n        </ol>\r\n      </div> <!-- /.content-header -->\r\n\r\n      \r\n\r\n      <div class=\"row\">\r\n        <div class=\"col-sm-3\"></div>\r\n        <div class=\"col-sm-12\">\r\n\r\n          <div class=\"portlet\">\r\n\r\n            <div class=\"portlet-header\">\r\n\r\n              <h3>\r\n                <i class=\"fa fa-tasks\"></i>\r\n                Student Details\r\n              </h3>\r\n\r\n            </div> <!-- /.portlet-header -->\r\n\r\n            <div class=\"portlet-content\">\r\n			\r\n			<div>\r\n		        ");
      if (_jspx_meth_s_005fif_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_s_005felse_005f0(_jspx_page_context))
        return;
      out.write("\r\n		    </div>\r\n		   ");

		    	if(classTeacherCheck.equals("Yes")){
		    		
		    
      out.write(" \r\n		  <form id=\"loadStudentFOrm\" action=\"LoadStudentForAttendance\" method=\"POST\" data-validate=\"parsley\" class=\"form parsley-form\">\r\n				\r\n                <div class=\"row\">\r\n                \r\n	                <div class=\"col-md-2\">\r\n						<input type=\"hidden\" class=\"form-control\" id= \"standardID\" name=\"standardID\" value=\"");
      out.print(StandardID);
      out.write("\" >\r\n						<input type=\"text\" class=\"form-control\" name=\"standard\" value=\"");
      out.print(StandardName);
      out.write("\" readonly=\"readonly\">\r\n								\r\n					</div>\r\n						\r\n					<div class=\"col-md-2\">\r\n					    <input type=\"hidden\" class=\"form-control\" name=\"divisionID\" value=\"");
      out.print(DivisionID);
      out.write("\" >\r\n						<input type=\"text\" class=\"form-control\" name=\"division\" value=\"");
      out.print(DivisionName);
      out.write("\" readonly=\"readonly\">	\r\n			        </div>\r\n		        \r\n               		<div class=\"col-md-2\">\r\n                		\r\n				  		");
      if (_jspx_meth_s_005fselect_005f0(_jspx_page_context))
        return;
      out.write("\r\n					</div>\r\n					\r\n	              	<div class=\"col-md-2\" > \r\n	               	");

						if(loadStudentSearch.equals("Enabled")){
					
      out.write("\r\n						");
      if (_jspx_meth_s_005fselect_005f1(_jspx_page_context))
        return;
      out.write("\r\n					");

						}else{
							
					
      out.write("\r\n					\r\n						 <select name=\"workingMonth\"  id=\"monthID\" class=\"form-control\">\r\n				            <option value=\"-1\">Select Month</option>\r\n				         </select>\r\n					");

						}
					
      out.write("\r\n               		</div>\r\n		        \r\n			        <div class=\"col-md-2\">\r\n						<button type=\"button\" class=\"btn btn-success\" onclick=\"return checkStandard(termID.value,monthID.value)\">Load Students</button>\r\n							\r\n					</div>\r\n					\r\n					<div class=\"col-md-2\">\r\n						<button type=\"button\" class=\"btn btn-warning\" onclick=\"checkStandard1(termID.value)\">Attendance Report</button>\r\n					</div>\r\n					\r\n				</div>\r\n			\r\n			<hr>\r\n			\r\n			<div class=\"tab-pane fade in active\">\r\n				");

					if(loadStudentSearch.equals("Enabled")){
				
      out.write("\r\n				<div class=\"row\" style=\"background:white;margin-left:0px;margin-right:0px;margin-bottom:20px;padding-top: 20px;\">\r\n		          \r\n		              <table id=\"\" class=\"table table-striped table-bordered dt-responsive nowrap\" cellspacing=\"0\" width=\"100%\">\r\n	                     <thead>\r\n	                        <tr>\r\n	                          <th>Roll No</th>\r\n	                        \r\n	                          <th>Student Name</th>\r\n	                          \r\n	                          <th>Present Days</th>\r\n				       	\r\n	                      	</tr>\r\n	                      </thead>\r\n	                  <tbody>\r\n	                      \r\n	                   ");
 
				       		for(StudentForm form : studentsList){
				       			
				       
      out.write("\r\n				        \r\n				       <tr id=\"newTRID");
      out.print(form.getStudentID());
      out.write("\" style=\"font-size: 14px;width: 6%;\">\r\n				       		\r\n				       		<td style=\"text-align: left;width: 6%;\">\r\n				       		<input type=\"hidden\" name=\"\" id=\"studentID");
      out.print(form.getStudentID() );
      out.write("\" value=\"");
      out.print(form.getStudentID());
      out.write("\">\r\n				       			");
      out.print(form.getRollNumber());
      out.write("\r\n				       		</td>	\r\n				       		\r\n				       		<td style=\"text-align: left;width: 25%;\">\r\n				       			");
      out.print(form.getStudentName());
      out.write("\r\n				       		</td>\r\n		                   	<td style=\"text-align: left;width: 15%;\">\r\n		                   		<input type=\"number\" class=\"form-control\" id=\"daysPresentID");
      out.print(form.getStudentID() );
      out.write("\" name=\"\" onkeyup=\"assignName('daysPresentID");
      out.print(form.getStudentID() );
      out.write('\'');
      out.write(',');
      out.print(form.getStudentID() );
      out.write(",'studentID");
      out.print(form.getStudentID() );
      out.write("','Attendance',");
      out.print(workingDays );
      out.write(",'spanID");
      out.print(form.getStudentID() );
      out.write("');\"> \r\n				       			<font style=\"color: red;\" id = \"spanID");
      out.print(form.getStudentID() );
      out.write("\"></font>\r\n				       		</td>\r\n					     	\r\n					   </tr> \r\n				        \r\n				        ");
 
				        	}
				        
      out.write("\r\n	                  \r\n	                   ");
 
				       		for(StudentForm form:NewStudentsList){
				       			
				       
      out.write("\r\n				        \r\n				       <tr id=\"newTRID");
      out.print(form.getStudentID());
      out.write("\" style=\"font-size: 14px;width: 6%;\">\r\n				       		\r\n				       		<td style=\"text-align: left;width: 6%;\">\r\n				       		<input type=\"hidden\" name=\"studAttndsID\" value=\"");
      out.print(form.getStudentAttendanceID() );
      out.write("\">\r\n				       			");
      out.print(form.getRollNumber());
      out.write("\r\n				       		</td>	\r\n				       		\r\n				       		<td style=\"text-align: left;width: 25%;\">\r\n				       			");
      out.print(form.getStudentName());
      out.write("\r\n				       		</td>\r\n		                   	<td style=\"text-align: left;width: 15%;\">\r\n		                   		<input type=\"number\" class=\"form-control\" name=\"editdaysPresentArr\" id=\"editdaysPresentArrID");
      out.print(form.getStudentID() );
      out.write("\" value=\"");
      out.print(form.getDaysPresent() );
      out.write("\" onkeyup=\"assignNameNew('editdaysPresentArrID");
      out.print(form.getStudentID() );
      out.write('\'');
      out.write(',');
      out.print(workingDays );
      out.write(",'newSpanID");
      out.print(form.getStudentID() );
      out.write("');\" > \r\n								<font style=\"color: red;\" id = \"newSpanID");
      out.print(form.getStudentID() );
      out.write("\"></font>\r\n							</td>\r\n					     	\r\n					  </tr> \r\n				        \r\n				        ");
 
				        	}
				        
      out.write("\r\n	                      </tbody>\r\n	                    </table>\r\n		                \r\n			        </div>\r\n			        <div class=\"form-group\" align=\"center\">\r\n				  <button type=\"button\" onclick=\"windowOpen1();\" class=\"btn btn-default\">Cancel</button>\r\n                  <button type=\"submit\" id = \"submitID\" class=\"btn btn-success\" id=\"submitID\" onclick=\"submitForm('submitID');\">Save</button>\r\n                </div>\r\n			       \r\n			       ");

						}
			       
      out.write("\r\n			      \r\n				 </div>\r\n				 </form>\r\n				 ");
} 
      out.write("\r\n				 \r\n             </div> <!-- /.portlet-content -->\r\n\r\n          </div> <!-- /.portlet -->\r\n          \r\n        </div> <!-- /.col -->\r\n\r\n      </div> <!-- /.row -->\r\n        \r\n	</div> <!-- /.content-container -->\r\n      \r\n  </div> <!-- /.content -->\r\n\r\n</div> <!-- /.container -->\r\n\r\n\r\n  ");
      out.write("\r\n  <script src=\"./js/libs/jquery-ui-1.9.2.custom.min.js\"></script>\r\n  <script src=\"./js/libs/bootstrap.min.js\"></script>\r\n\r\n  <!--[if lt IE 9]>\r\n  <script src=\"./js/libs/excanvas.compiled.js\"></script>\r\n  <![endif]-->\r\n  \r\n  <!-- Plugin JS -->\r\n  <script src=\"./js/plugins/icheck/jquery.icheck.js\"></script>\r\n  <script src=\"./js/plugins/select2/select2.js\"></script>\r\n  <script src=\"./js/libs/raphael-2.1.2.min.js\"></script>\r\n  <script src=\"./js/plugins/morris/morris.min.js\"></script>\r\n  <script src=\"./js/plugins/sparkline/jquery.sparkline.min.js\"></script>\r\n  <script src=\"./js/plugins/nicescroll/jquery.nicescroll.min.js\"></script>\r\n  <script src=\"./js/plugins/fullcalendar/fullcalendar.min.js\"></script>\r\n\r\n  <!-- App JS -->\r\n  <script src=\"./js/target-admin.js\"></script>\r\n  \r\n  <!-- Plugin JS -->\r\n  <script src=\"./js/demos/dashboard.js\"></script>\r\n  <script src=\"./js/demos/calendar.js\"></script>\r\n  <script src=\"./js/demos/charts/morris/area.js\"></script>\r\n  <script src=\"./js/demos/charts/morris/donut.js\"></script>\r\n");
      out.write("  <script src=\"./js/plugins/datepicker/bootstrap-datepicker.js\"></script>\r\n  \r\n</body>\r\n</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f0_reused = false;
    try {
      _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f0.setParent(null);
      // /studentAttendance.jsp(499,10) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f0.setTest("hasActionErrors()");
      int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f0);
        }
        do {
          out.write("\r\n					<center>\r\n						<font style=\"color: red; font-size:16px;\">");
          if (_jspx_meth_s_005factionerror_005f0(_jspx_th_s_005fif_005f0, _jspx_page_context))
            return true;
          out.write("</font>\r\n					</center>\r\n				");
          int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      _jspx_th_s_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005factionerror_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:actionerror
    org.apache.struts2.views.jsp.ui.ActionErrorTag _jspx_th_s_005factionerror_005f0 = (org.apache.struts2.views.jsp.ui.ActionErrorTag) _005fjspx_005ftagPool_005fs_005factionerror_005fnobody.get(org.apache.struts2.views.jsp.ui.ActionErrorTag.class);
    boolean _jspx_th_s_005factionerror_005f0_reused = false;
    try {
      _jspx_th_s_005factionerror_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005factionerror_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
      int _jspx_eval_s_005factionerror_005f0 = _jspx_th_s_005factionerror_005f0.doStartTag();
      if (_jspx_th_s_005factionerror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005factionerror_005fnobody.reuse(_jspx_th_s_005factionerror_005f0);
      _jspx_th_s_005factionerror_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005factionerror_005f0, _jsp_getInstanceManager(), _jspx_th_s_005factionerror_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005felse_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:else
    org.apache.struts2.views.jsp.ElseTag _jspx_th_s_005felse_005f0 = (org.apache.struts2.views.jsp.ElseTag) _005fjspx_005ftagPool_005fs_005felse.get(org.apache.struts2.views.jsp.ElseTag.class);
    boolean _jspx_th_s_005felse_005f0_reused = false;
    try {
      _jspx_th_s_005felse_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005felse_005f0.setParent(null);
      int _jspx_eval_s_005felse_005f0 = _jspx_th_s_005felse_005f0.doStartTag();
      if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005felse_005f0);
        }
        do {
          out.write("\r\n					<center>\r\n						<font style=\"color: green;font-size:16px;\">");
          if (_jspx_meth_s_005factionmessage_005f0(_jspx_th_s_005felse_005f0, _jspx_page_context))
            return true;
          out.write("</font>\r\n					</center>\r\n				");
          int evalDoAfterBody = _jspx_th_s_005felse_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005felse_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005felse_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005felse.reuse(_jspx_th_s_005felse_005f0);
      _jspx_th_s_005felse_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005felse_005f0, _jsp_getInstanceManager(), _jspx_th_s_005felse_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005factionmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005felse_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:actionmessage
    org.apache.struts2.views.jsp.ui.ActionMessageTag _jspx_th_s_005factionmessage_005f0 = (org.apache.struts2.views.jsp.ui.ActionMessageTag) _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.get(org.apache.struts2.views.jsp.ui.ActionMessageTag.class);
    boolean _jspx_th_s_005factionmessage_005f0_reused = false;
    try {
      _jspx_th_s_005factionmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005factionmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005felse_005f0);
      int _jspx_eval_s_005factionmessage_005f0 = _jspx_th_s_005factionmessage_005f0.doStartTag();
      if (_jspx_th_s_005factionmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.reuse(_jspx_th_s_005factionmessage_005f0);
      _jspx_th_s_005factionmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005factionmessage_005f0, _jsp_getInstanceManager(), _jspx_th_s_005factionmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fselect_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:select
    org.apache.struts2.views.jsp.ui.SelectTag _jspx_th_s_005fselect_005f0 = (org.apache.struts2.views.jsp.ui.SelectTag) _005fjspx_005ftagPool_005fs_005fselect_0026_005fonchange_005fname_005flist_005fid_005fheaderValue_005fheaderKey_005fclass_005fnobody.get(org.apache.struts2.views.jsp.ui.SelectTag.class);
    boolean _jspx_th_s_005fselect_005f0_reused = false;
    try {
      _jspx_th_s_005fselect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fselect_005f0.setParent(null);
      // /studentAttendance.jsp(530,8) name = list type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setList(" #{'Term I':'Term I','Term II':'Term II'}");
      // /studentAttendance.jsp(530,8) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setCssClass("form-control");
      // /studentAttendance.jsp(530,8) name = headerKey type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setHeaderKey("-1");
      // /studentAttendance.jsp(530,8) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setId("termID");
      // /studentAttendance.jsp(530,8) name = headerValue type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setHeaderValue("Select Term");
      // /studentAttendance.jsp(530,8) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setName("term");
      // /studentAttendance.jsp(530,8) name = onchange type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f0.setOnchange("retrieveworkingMonth(this.value, standardID.value);");
      int _jspx_eval_s_005fselect_005f0 = _jspx_th_s_005fselect_005f0.doStartTag();
      if (_jspx_th_s_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fselect_0026_005fonchange_005fname_005flist_005fid_005fheaderValue_005fheaderKey_005fclass_005fnobody.reuse(_jspx_th_s_005fselect_005f0);
      _jspx_th_s_005fselect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fselect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fselect_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:select
    org.apache.struts2.views.jsp.ui.SelectTag _jspx_th_s_005fselect_005f1 = (org.apache.struts2.views.jsp.ui.SelectTag) _005fjspx_005ftagPool_005fs_005fselect_0026_005fname_005flist_005fid_005fheaderValue_005fheaderKey_005fclass_005fnobody.get(org.apache.struts2.views.jsp.ui.SelectTag.class);
    boolean _jspx_th_s_005fselect_005f1_reused = false;
    try {
      _jspx_th_s_005fselect_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fselect_005f1.setParent(null);
      // /studentAttendance.jsp(537,6) name = list type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setList("MonthList");
      // /studentAttendance.jsp(537,6) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setName("workingMonth");
      // /studentAttendance.jsp(537,6) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setId("monthID");
      // /studentAttendance.jsp(537,6) name = class type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setCssClass("form-control");
      // /studentAttendance.jsp(537,6) name = headerKey type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setHeaderKey("-1");
      // /studentAttendance.jsp(537,6) name = headerValue type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fselect_005f1.setHeaderValue("Select Month");
      int _jspx_eval_s_005fselect_005f1 = _jspx_th_s_005fselect_005f1.doStartTag();
      if (_jspx_th_s_005fselect_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fselect_0026_005fname_005flist_005fid_005fheaderValue_005fheaderKey_005fclass_005fnobody.reuse(_jspx_th_s_005fselect_005f1);
      _jspx_th_s_005fselect_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fselect_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fselect_005f1_reused);
    }
    return false;
  }
}
