/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-30 05:21:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kovidRMS.form.*;
import com.kovidRMS.daoInf.*;
import com.kovidRMS.daoImpl.*;
import java.util.*;

public final class topMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.kovidRMS.daoInf");
    _jspx_imports_packages.add("com.kovidRMS.daoImpl");
    _jspx_imports_packages.add("com.kovidRMS.form");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n \r\n\r\n\r\n\r\n<!DOCTYPE html>\r\n<html class=\"no-js\"> \r\n<head>\r\n	");

		LoginForm form = (LoginForm) session.getAttribute("USER");
	
		int userID = form.getUserID();
		
		LoginDAOInf daoInf = new LoginDAOImpl();
		
		HashMap<Integer, String> organizationList = daoInf.getOrganization();
	
      out.write("\r\n\r\n	");
 if(form.getMedium().equals("mr")){ 
      out.write("\r\n		<title>डॅशबोर्ड - SkoolUp</title>\r\n	");
}else{ 
      out.write("\r\n		<title>Dashboard - SkoolUp</title>\r\n	");
} 
      out.write("\r\n\r\n<!-- Favicon -->\r\n  <link rel=\"shortcut icon\" href=\"images/favicon.jpg\">\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"viewport\" content=\"width=device-width\">\r\n\r\n<script type=\"text/javascript\">\r\n	function submitChangeOrganizationForm(organizationID){\r\n		\r\n		$('html, body').animate({\r\n	        scrollTop: $('body').offset().top\r\n	   }, 1000);\r\n		\r\n		$('body').css('background', '#FCFAF5');\r\n		$(\".container\").css(\"opacity\",\"0.2\");\r\n		$(\"#loader\").show();\r\n		$(\"body\").find(\"button\").attr(\"disabled\",\"disabled\"); \r\n    	\r\n		$(\"#changeOrganizationID\").val(organizationID);\r\n		$(\"#changeOrganizationForm\").submit();	\r\n	}\r\n</script>\r\n\r\n</head>\r\n\r\n<body>\r\n\r\n  <div class=\"mainbar\" id=\"fixedDiv\">\r\n\r\n  <div class=\"container\">\r\n  \r\n	<ul class=\"nav navbar-nav navbar-right\">     \r\n	 \r\n	 ");
  if(form.getRole().equals("superAdmin")){  
      out.write("\r\n	  	\r\n		<li class=\"dropdown navbar-profile\">\r\n         <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"javascript:;\" style=\"color: white;\">\r\n          <label style=\"color: white\">");
 if(form.getMedium().equals("mr")){ 
      out.write(" संस्था  ");
}else{ 
      out.write(" Organization ");
} 
      out.write(" </label>\r\n         \r\n         	<span class=\"navbar-profile-label\">rod@rod.me &nbsp;</span>\r\n            <i class=\"fa fa-caret-down\"></i>\r\n          </a>\r\n          \r\n          <ul class=\"dropdown-menu\" role=\"menu\">\r\n\r\n			<form action=\"ChangeOrganization\" method=\"POST\" id=\"changeOrganizationForm\" >\r\n				<input type=\"hidden\" name=\"changedOrganizationID\" id=\"changeOrganizationID\" >\r\n		\r\n			");
 for(Integer organization : organizationList.keySet()){ 
      out.write("\r\n				<li>\r\n		            <a href=\"javascript:submitChangeOrganizationForm('");
      out.print( organization );
      out.write("');\"><i class=\"fa fa-user\"></i>&nbsp;&nbsp;");
      out.print(organizationList.get(organization));
      out.write("</a>\r\n		        </li>\r\n			");
 } 
      out.write("		\r\n			\r\n			</form>\r\n          </ul>\r\n\r\n        </li>\r\n	\r\n	");
 } 
      out.write("\r\n			\r\n        <li class=\"dropdown navbar-profile\">\r\n          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"javascript:;\" style=\"color: white;\">\r\n           <!--  <img src=\"./img/avatars/avatar-1-xs.jpg\" class=\"navbar-profile-avatar\" alt=\"\"> -->\r\n           	");

              	if(daoInf.retrieveProfilePic(form.getUserID()) == null || daoInf.retrieveProfilePic(form.getUserID()) == ""){ 
	       	
      out.write("\r\n	              \r\n	      	<img src=\"images/user.png\" alt=\"Profile Pic\" style=\"height: 30px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
      out.print( form.getFullName() );
      out.write("\r\n	               \r\n	       	");
  }else if(daoInf.retrieveProfilePic(form.getUserID()).isEmpty()){ 
      out.write("\r\n	            	\r\n	            	<img src=\"images/user.png\" alt=\"Profile Pic\" style=\"height: 30px;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
      out.print( form.getFullName() );
      out.write("\r\n	            	\r\n	        ");
  }else{ 
      out.write("\r\n	                \r\n	      	<img src=\"");
      out.print( daoInf.retrieveProfilePic(form.getUserID()) );
      out.write("\" style=\"height: 30px;\" alt=\"Profile Pic\">");
      out.print( form.getFullName() );
      out.write("\r\n	                \r\n	        ");

	            	}
	        
      out.write("\r\n            <span class=\"navbar-profile-label\">rod@rod.me &nbsp;</span>\r\n            <i class=\"fa fa-caret-down\"></i>\r\n          </a>\r\n\r\n          <ul class=\"dropdown-menu\" role=\"menu\">\r\n\r\n			<li>");
 if(form.getMedium().equals("mr")){ 
      out.write("\r\n           		<a href=\"RenderEditProfile\"><i class=\"fa fa-user\"></i>&nbsp;&nbsp;माझे प्रोफाइल</a>\r\n            ");
}else{ 
      out.write("\r\n				<a href=\"RenderEditProfile\"><i class=\"fa fa-user\"></i>&nbsp;&nbsp;My Profile</a>\r\n			");
} 
      out.write("\r\n              \r\n            </li>\r\n            \r\n            <li class=\"divider\"></li>\r\n\r\n            <li>\r\n            ");
 if(form.getMedium().equals("mr")){ 
      out.write("\r\n           		<a href=\"Logout\"><i class=\"fa fa-sign-out\"></i>&nbsp;&nbsp;लॉगआउट</a>\r\n            ");
}else{ 
      out.write("\r\n				<a href=\"Logout\"><i class=\"fa fa-sign-out\"></i>&nbsp;&nbsp;Logout</a>\r\n			");
} 
      out.write("\r\n\r\n            </li>\r\n\r\n          </ul>\r\n\r\n        </li>\r\n\r\n      </ul>\r\n    <button type=\"button\" class=\"btn mainbar-toggle\" data-toggle=\"collapse\" data-target=\".mainbar-collapse\">\r\n      <i class=\"fa fa-bars\"></i>\r\n    </button>\r\n\r\n    <div class=\"mainbar-collapse collapse\">\r\n\r\n      <ul class=\"nav navbar-nav mainbar-nav\">\r\n	\r\n      ");

       	if(form.getRole().equals("officeAdmin")){
      
      out.write(" \r\n        <li id=\"leavingCertificateLiID\">\r\n          <a href=\"RenderloadLeavingStudent\">\r\n            <i class=\"fa fa-desktop\"></i>\r\n      		");
 if(form.getMedium().equals("mr")){ 
      out.write(" लसी/टीसी  ");
}else{ 
      out.write(" LC/TC ");
} 
      out.write("      \r\n          </a>\r\n        </li>\r\n      \r\n      ");
 }else if(form.getRole().equals("librarian")){  
      out.write(" \r\n      \r\n      	<li id=\"dashboardLiID\">\r\n            <a href=\"welcome.jsp\">\r\n              <i class=\"fa fa-desktop\"></i>\r\n              Dashboard\r\n            </a>\r\n         </li>\r\n        <li class=\"dropdown \" id=\"administrationLiID\">\r\n          <a href=\"#about\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\r\n            <i class=\"fa fa-cogs\"></i>\r\n            Administration\r\n            <span class=\"caret\"></span>\r\n          </a>\r\n\r\n          <ul class=\"dropdown-menu\">   \r\n         	 <li>\r\n	            <a href=\"RenderConfigureRules\">\r\n	             <i class=\"fa fa-building\"></i> \r\n	              &nbsp;&nbsp;Rules\r\n	            </a> \r\n              </li> \r\n              \r\n             <li class=\"dropdown-submenu\">\r\n              <a tabindex=\"-1\" href=\"#\">\r\n              <i class=\"fa fa-user\"></i> \r\n              &nbsp;&nbsp;Configuration\r\n              </a>\r\n\r\n              <ul class=\"dropdown-menu\">\r\n                <li>\r\n                  <a href=\"configurePVBookType.jsp\">\r\n                  <i class=\"fa fa-user\"></i> \r\n");
      out.write("                  	&nbsp;&nbsp;Manage Book Type\r\n                  </a>\r\n                </li>\r\n\r\n                <li>\r\n                  <a href=\"configurePVGenre.jsp\">\r\n                  <i class=\"fa fa-user\"></i> \r\n                  &nbsp;&nbsp;Manage Genre\r\n                  </a>\r\n                </li> \r\n                \r\n                <li>\r\n                  <a href=\"RenderConfigureSection\">\r\n                  <i class=\"fa fa-user\"></i> \r\n                  &nbsp;&nbsp;Manage Section\r\n                  </a>\r\n                </li>\r\n                \r\n                <li>\r\n                  <a href=\"configurePVVendors.jsp\">\r\n                  <i class=\"fa fa-user\"></i> \r\n                  &nbsp;&nbsp;Manage Vendors\r\n                  </a>\r\n                </li>\r\n              </ul>\r\n              \r\n             </li>\r\n             \r\n            </ul>\r\n          </li>\r\n        <li class=\"dropdown \"id=\"inventoryLiID\">\r\n	       <a href=\"#about\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\r\n");
      out.write("	          <i class=\"fa fa-book\"></i>\r\n	           Inventory\r\n	           <span class=\"caret\"></span>\r\n	       </a>\r\n	      <ul class=\"dropdown-menu\">   \r\n            \r\n	        <li class=\"dropdown-submenu\">\r\n	           <a href=\"\">\r\n	            <i class=\"fa fa-book\"></i> \r\n	             &nbsp;&nbsp;Books \r\n	            </a>    \r\n	        <ul class=\"dropdown-menu\">   \r\n              <li>\r\n	           <a href=\"RenderManageBook\">\r\n	             <i class=\"fa fa-book\"></i> \r\n	              &nbsp;&nbsp;New Book\r\n	           </a>\r\n	          </li>\r\n	              \r\n	          <li>\r\n	            <a href=\"RenderBookList\">\r\n	              <i class=\"fa fa-file-text-o\"></i> \r\n	              &nbsp;&nbsp;Manage Book\r\n	             </a>\r\n	          </li>\r\n	          \r\n	          <li>\r\n	           <a href=\"RenderMoveBook\">\r\n	             <i class=\"fa fa-book\"></i> \r\n	              &nbsp;&nbsp;Move Books\r\n	           </a>\r\n	          </li>\r\n	          \r\n			</ul>\r\n		   </li>\r\n		   \r\n		   <li class=\"\">\r\n	           <a href=\"RenderManageCupboardShelves\">\r\n");
      out.write("	            <i class=\"fa fa-table\"></i> \r\n	             &nbsp;&nbsp;Cupboards  \r\n	            </a>    \r\n	       </li>\r\n	        \r\n		  </ul>\r\n	    </li>\r\n       	<li class=\"dropdown \" id=\"issueLiID\">\r\n          <a href=\"#about\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\r\n            <i class=\"fa fa-desktop\"></i>\r\n            Issue\r\n          </a>\r\n          \r\n          <ul class=\"dropdown-menu\">   \r\n            \r\n	        <li class=\"\">\r\n	           <a href=\"RenderconfigureStudentIssue\">\r\n	            <i class=\"fa fa-user\"></i> \r\n	             &nbsp;&nbsp;Students \r\n	            </a>    \r\n	       </li>\r\n		   \r\n		   <li class=\"\">\r\n	           <a href=\"RenderconfigureStaffIssue\">\r\n	            <i class=\"fa fa-user\"></i> \r\n	             &nbsp;&nbsp;Staff  \r\n	            </a>    \r\n	       </li>\r\n	       \r\n		  </ul>\r\n        </li>\r\n           \r\n	     <li class=\"dropdown \" id=\"reportLiID\">\r\n	          <a href=\"#about\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\r\n	            <i class=\"fa fa-line-chart\"></i>\r\n");
      out.write("	             Reports\r\n	             <span class=\"caret\"></span>\r\n	          </a>\r\n	          \r\n	          <ul class=\"dropdown-menu\">   \r\n            	<li >\r\n	              <a tabindex=\"-1\" href=\"RenderInventoryReport\">\r\n	              <i class=\"fa fa-file-text-o\"></i> \r\n	              &nbsp;&nbsp; Inventory Report\r\n	              </a>\r\n	            </li>\r\n	           \r\n	            <li>\r\n                  <a href=\"RenderStudentsReport\">\r\n                  <i class=\"fa fa-file-text-o\"></i> \r\n                  &nbsp;&nbsp;Student Report\r\n                  </a>\r\n                </li> \r\n                \r\n                <li>\r\n                  <a href=\"RenderStaffReport\">\r\n                  <i class=\"fa fa-file-text-o\"></i> \r\n                  &nbsp;&nbsp;Staff Report\r\n                  </a>\r\n                </li> \r\n             </ul> \r\n       	</li>\r\n       	   \r\n      ");
 }else{ 
      out.write(" \r\n        \r\n         <li id=\"dashboardLiID\">\r\n            <a href=\"welcome.jsp\">\r\n              <i class=\"fa fa-desktop\"></i>\r\n             ");
 if(form.getMedium().equals("mr")){ 
      out.write(" डॅशबोर्ड  ");
}else{ 
      out.write(" Dashboard ");
} 
      out.write(" \r\n            </a>\r\n         </li>\r\n         \r\n       ");
  if(form.getRole().equals("superAdmin")){  
      out.write(" \r\n\r\n        <li class=\"dropdown \" id=\"administrationLiID\">\r\n          <a href=\"#about\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\r\n            <i class=\"fa fa-cogs\"></i>\r\n            ");
 if(form.getMedium().equals("mr")){ 
      out.write(" ऍडमिनिस्ट्रेशन  ");
}else{ 
      out.write(" Administration ");
} 
      out.write(" \r\n            <span class=\"caret\"></span>\r\n          </a>\r\n\r\n          <ul class=\"dropdown-menu\">   \r\n            <li class=\"dropdown-submenu\">\r\n              <a tabindex=\"-1\" href=\"#\">\r\n              <i class=\"fa fa-user\"></i> \r\n              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" यूझर   ");
}else{ 
      out.write(" Users ");
} 
      out.write(" \r\n              </a>\r\n\r\n              <ul class=\"dropdown-menu\">\r\n                <li>\r\n                  <a href=\"addUser.jsp\">\r\n                  <i class=\"fa fa-user\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" युझर नोंदवा   ");
}else{ 
      out.write(" Register User ");
} 
      out.write(" \r\n                  </a>\r\n                </li>\r\n\r\n                <li>\r\n                  <a href=\"editUserList.jsp\">\r\n                  <i class=\"fa fa-user\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write("युझर व्यवस्थापन  ");
}else{ 
      out.write(" Manage User ");
} 
      out.write(" \r\n                  </a>\r\n                </li> \r\n              </ul>\r\n              \r\n             </li>\r\n             <li>\r\n	              <a href=\"manageOrganization.jsp\">\r\n	              <i class=\"fa fa-building\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" संस्था  ");
}else{ 
      out.write(" Organization ");
} 
      out.write(" \r\n	              </a> \r\n              </li>\r\n              \r\n              <li class=\"dropdown-submenu\">\r\n	              <a href=\"#\">\r\n	              <i class=\"fa fa-calendar\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" शैक्षणिक वर्ष   ");
}else{ 
      out.write(" Academic Year ");
} 
      out.write(" \r\n	              </a>\r\n	              \r\n	              <ul class=\"dropdown-menu\">\r\n                <li>\r\n                  <a href=\"RenderAcademicYear\">\r\n                  <i class=\"fa fa-calendar\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" शैक्षणिक वर्ष व्यवस्थापन   ");
}else{ 
      out.write(" Manage Academic Year ");
} 
      out.write(" \r\n                  </a>\r\n                </li>\r\n\r\n                <li>\r\n                  <a href=\"RenderconfigureAcademicYear\">\r\n                  <i class=\"fa fa-calendar\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" शैक्षणिक वर्ष कॉन्फीग्युर करा   ");
}else{ 
      out.write(" Configure Academic Year ");
} 
      out.write(" \r\n                  </a>\r\n                </li> \r\n                \r\n                <li>\r\n                  <a href=\"RenderconfigureExamination\">\r\n                  <i class=\"fa fa-calendar\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" वेळापत्रक कॉन्फीग्युर करा   ");
}else{ 
      out.write(" Configure Examinations ");
} 
      out.write(" \r\n                  </a>\r\n                </li> \r\n                \r\n                <li>\r\n                  <a href=\"RenderconfigureSubjectAssessment\">\r\n                  <i class=\"fa fa-calendar\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" विषय मूल्यमापन कॉन्फीग्युर करा   ");
}else{ 
      out.write(" Configure Subject Assessment ");
} 
      out.write(" \r\n                  </a>\r\n                </li> \r\n              </ul>\r\n              </li> \r\n              \r\n              <li class=\"dropdown-submenu\">\r\n	              <a tabindex=\"-1\" href=\"#\">\r\n	              <i class=\"fa fa-users\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" इयत्ता  ");
}else{ 
      out.write(" Classes ");
} 
      out.write(" \r\n	              </a>\r\n	              \r\n	           <ul class=\"dropdown-menu\">\r\n                <li>\r\n                  <a href=\"RenderManageStandard\">\r\n                  <i class=\"fa fa-users\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" इयत्ता व्यवस्थापन   ");
}else{ 
      out.write(" Manage Standard ");
} 
      out.write(" \r\n                  </a>\r\n                </li>\r\n\r\n                <li>\r\n                  <a href=\"RenderDivision\">\r\n                  <i class=\"fa fa-users\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" तुकडी मूल्यमापन   ");
}else{ 
      out.write(" Manage Division ");
} 
      out.write(" \r\n                  </a>\r\n                </li> \r\n              </ul>\r\n              </li> \r\n              \r\n              <li>\r\n	              <a href=\"manageSubject.jsp\">\r\n	              <i class=\"fa fa-book\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" विषय   ");
}else{ 
      out.write(" Subjects ");
} 
      out.write(" \r\n	              </a>\r\n	          \r\n              </li> \r\n              \r\n              <li>\r\n	              <a href=\"manageCommutation.jsp\">\r\n	              <i class=\"fa fa-bus\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" प्रवास   ");
}else{ 
      out.write(" Commutation ");
} 
      out.write(" \r\n	              </a> \r\n              </li>\r\n              \r\n              <li>\r\n	              <a href=\"RenderManageTimeTable\">\r\n	              <i class=\"fa fa-calendar-o\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" वेळापत्रक व्यवस्थापन  ");
}else{ 
      out.write(" Manage TimeTable ");
} 
      out.write(" \r\n	              </a> \r\n              </li>\r\n              \r\n              <li>\r\n	              <a href=\"RenderImportExport\">\r\n	              <i class=\"fa fa-calendar-o\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" आयात/निर्यात   ");
}else{ 
      out.write(" Import/Export ");
} 
      out.write(" \r\n	              </a> \r\n              </li>\r\n              \r\n             <!--  <li>\r\n	              <a href=\"RenderElection\">\r\n	              <i class=\"fa fa-calendar-o\"></i> \r\n	              &nbsp;&nbsp;Manage Voting\r\n	              </a> \r\n              </li>  -->\r\n              \r\n            </ul>\r\n            </li>\r\n            \r\n         ");
 }else if(form.getRole().equals("administrator")){ 
      out.write("\r\n        		\r\n        	  <li class=\"dropdown \" id=\"administrationLiID\">\r\n              <a href=\"#about\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\r\n                <i class=\"fa fa-cogs\"></i>\r\n               ");
 if(form.getMedium().equals("mr")){ 
      out.write(" ऍडमिनिस्ट्रेशन  ");
}else{ 
      out.write(" Administration ");
} 
      out.write(" \r\n                <span class=\"caret\"></span>\r\n              </a>\r\n\r\n              <ul class=\"dropdown-menu\">   \r\n                <li class=\"dropdown-submenu\">\r\n              <a tabindex=\"-1\" href=\"#\">\r\n              <i class=\"fa fa-user\"></i> \r\n              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" युझर  ");
}else{ 
      out.write(" Users ");
} 
      out.write(" \r\n              </a>\r\n\r\n              <ul class=\"dropdown-menu\">\r\n                <li>\r\n                  <a href=\"addUser.jsp\">\r\n                  <i class=\"fa fa-user\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" युझर नोंदणी   ");
}else{ 
      out.write(" Register User ");
} 
      out.write("\r\n                  </a>\r\n                </li>\r\n\r\n                <li>\r\n                  <a href=\"editUserList.jsp\">\r\n                  <i class=\"fa fa-user\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write("युझर व्यवस्थापन  ");
}else{ 
      out.write(" Manage User ");
} 
      out.write(" \r\n                  </a>\r\n                </li> \r\n              </ul>\r\n              \r\n             </li>\r\n                  <li class=\"dropdown-submenu\">\r\n    	              <a href=\"#\">\r\n    	              <i class=\"fa fa-calendar\"></i> \r\n    	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" शैक्षणिक वर्ष   ");
}else{ 
      out.write(" Academic Year ");
} 
      out.write(" \r\n    	              </a>\r\n    	              \r\n    	              <ul class=\"dropdown-menu\">\r\n                    <li>\r\n                      <a href=\"RenderAcademicYear\">\r\n                      <i class=\"fa fa-calendar\"></i> \r\n                      &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" शैक्षणिक वर्ष व्यवस्थापन   ");
}else{ 
      out.write(" Manage Academic Year ");
} 
      out.write(" \r\n                      </a>\r\n                    </li>\r\n\r\n                    <li>\r\n                      <a href=\"RenderconfigureAcademicYear\">\r\n                      <i class=\"fa fa-calendar\"></i> \r\n                      &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" शैक्षणिक वर्ष कॉन्फीग्युर करा   ");
}else{ 
      out.write(" Configure Academic Year ");
} 
      out.write("\r\n                      </a>\r\n                    </li> \r\n                    \r\n                    <li>\r\n                      <a href=\"RenderconfigureExamination\">\r\n                      <i class=\"fa fa-calendar\"></i> \r\n                      &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" वेळापत्रक कॉन्फीग्युर करा   ");
}else{ 
      out.write(" Configure Examinations ");
} 
      out.write("\r\n                      </a>\r\n                    </li> \r\n                    \r\n                    <li>\r\n	                  <a href=\"RenderconfigureSubjectAssessment\">\r\n	                  <i class=\"fa fa-calendar\"></i> \r\n	                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" विषय मूल्यमापन कॉन्फीग्युर करा   ");
}else{ 
      out.write(" Configure Subject Assessment ");
} 
      out.write(" \r\n	                  </a>\r\n	                </li>\r\n	                  \r\n                  </ul>\r\n                  </li> \r\n                  \r\n                <li class=\"dropdown-submenu\">\r\n	              <a tabindex=\"-1\" href=\"#\">\r\n	              <i class=\"fa fa-users\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" इयत्ता  ");
}else{ 
      out.write(" Classes ");
} 
      out.write(" \r\n	              </a>\r\n	              \r\n	           <ul class=\"dropdown-menu\">\r\n                <li>\r\n                  <a href=\"RenderManageStandard\">\r\n                  <i class=\"fa fa-users\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" इयत्ता व्यवस्थापन   ");
}else{ 
      out.write(" Manage Standard ");
} 
      out.write(" \r\n                  </a>\r\n                </li>\r\n\r\n                <li>\r\n                  <a href=\"RenderDivision\">\r\n                  <i class=\"fa fa-users\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" तुकडी मूल्यमापन   ");
}else{ 
      out.write(" Manage Division ");
} 
      out.write(" \r\n                  </a>\r\n                </li> \r\n              </ul>\r\n              </li> \r\n              \r\n              <li>\r\n	              <a href=\"manageSubject.jsp\">\r\n	              <i class=\"fa fa-book\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" विषय   ");
}else{ 
      out.write(" Subjects ");
} 
      out.write(" \r\n	              </a>\r\n	          \r\n              </li> \r\n              \r\n              <li>\r\n    	              <a href=\"manageCommutation.jsp\">\r\n    	              <i class=\"fa fa-bus\"></i> \r\n    	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" प्रवास   ");
}else{ 
      out.write(" Commutation ");
} 
      out.write(" \r\n    	              </a> \r\n                  </li>\r\n                  \r\n                  <li>\r\n    	              <a href=\"RenderManageTimeTable\">\r\n    	              <i class=\"fa fa-calendar-o\"></i> \r\n    	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" वेळापत्रक व्यवस्थापन  ");
}else{ 
      out.write(" Manage TimeTable ");
} 
      out.write("\r\n    	              </a> \r\n                  </li>\r\n                  \r\n                  <li>\r\n		              <a href=\"RenderImportExport\">\r\n		              <i class=\"fa fa-calendar-o\"></i> \r\n		              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" आयात/निर्यात   ");
}else{ 
      out.write(" Import/Export ");
} 
      out.write(" \r\n		              </a> \r\n	              </li>\r\n                  \r\n             <!--  <li>\r\n	              <a href=\"RenderElection\">\r\n	              <i class=\"fa fa-calendar-o\"></i> \r\n	              &nbsp;&nbsp;Manage Voting\r\n	              </a> \r\n              </li>  -->\r\n              \r\n                </ul>\r\n                </li>\r\n        ");
 } 
      out.write("  \r\n            \r\n            <li class=\"dropdown \" id=\"studentLiID\">\r\n	          <a href=\"#about\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\r\n	            <i class=\"fa fa-graduation-cap\"></i>\r\n	            ");
 if(form.getMedium().equals("mr")){ 
      out.write(" विद्यार्थी  ");
}else{ 
      out.write(" Students ");
} 
      out.write("  \r\n	             <span class=\"caret\"></span>\r\n	          </a>\r\n	          \r\n	          <ul class=\"dropdown-menu\">   \r\n            \r\n	            <li >\r\n	              <a href=\"RenderaddStudent\">\r\n	              <i class=\"fa fa-user\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" विद्यार्थी नोंदणी  ");
}else{ 
      out.write(" Register Students ");
} 
      out.write(" \r\n	              </a>\r\n	            </li>\r\n	           \r\n	           <li >\r\n	              <a href=\"RenderManageEditStudentList\">\r\n	              <i class=\"fa fa-user\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" विद्यार्थी व्यवस्थापन  ");
}else{ 
      out.write(" Manage Students ");
} 
      out.write(" \r\n	              </a>\r\n	            </li>\r\n	            \r\n	            <li >\r\n	              <a href=\"RenderStudentAttendance\">\r\n	              <i class=\"fa fa-user\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" विद्यार्थी उपस्थिती   ");
}else{ 
      out.write(" Student Attendance ");
} 
      out.write(" \r\n	              </a>\r\n	            </li>\r\n	            \r\n	             <li >\r\n	              <a href=\"RendertransferStudent\">\r\n	              <i class=\"fa fa-user\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" विद्यार्थी ट्रान्स्फर  ");
}else{ 
      out.write(" Transfer Students ");
} 
      out.write(" \r\n	              </a>\r\n	            </li>\r\n	            \r\n	            <li >\r\n	              <a href=\"RenderBulkUpdateStudent\">\r\n	              <i class=\"fa fa-user\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" विद्यार्थ्यांचे बल्क अपडेट  ");
}else{ 
      out.write(" Bulk Update Students ");
} 
      out.write(" \r\n	              </a>\r\n	            </li>\r\n	            \r\n	           </ul>\r\n	         </li>\r\n        	\r\n         <li class=\"dropdown \"id=\"myExamLiID\">\r\n	          <a href=\"#about\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\r\n	            <i class=\"fa fa-book\"></i>\r\n	            ");
 if(form.getMedium().equals("mr")){ 
      out.write(" परीक्षा   ");
}else{ 
      out.write(" Examinations ");
} 
      out.write("  \r\n	             <span class=\"caret\"></spaSubjectsn>\r\n	          </a>\r\n	          \r\n	          <ul class=\"dropdown-menu\">   \r\n            \r\n	            <li class=\"dropdown-submenu\">\r\n	              <a tabindex=\"-1\" href=\"#\">\r\n	              <i class=\"fa fa-book\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" माझे विषय   ");
}else{ 
      out.write(" My Subjects ");
} 
      out.write(" \r\n	              </a>\r\n	              \r\n	              <ul class=\"dropdown-menu\">\r\n	                <li>\r\n	                  <a href=\"RenderConfigureMySubject\">\r\n	                  <i class=\"fa fa-file-text-o\"></i> \r\n	                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" शैक्षणिक  ");
}else{ 
      out.write(" Scholastic ");
} 
      out.write(" \r\n	                  </a>\r\n	                </li>\r\n	\r\n	                <li>\r\n	                  <a href=\"RenderConfigureCoScholastic\">\r\n	                  <i class=\"fa fa-file-text-o\"></i> \r\n	                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" सह-शैक्षणिक  ");
}else{ 
      out.write(" Co-scholastic ");
} 
      out.write(" \r\n	                  </a>\r\n	                </li> \r\n	                \r\n	                <li>\r\n	                  <a href=\"RenderConfigureExtraCurricularActivity\">\r\n	                  <i class=\"fa fa-file-text-o\"></i> \r\n	                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" अभ्यासेतर उपक्रम  ");
}else{ 
      out.write(" Extra-curricular Activity ");
} 
      out.write(" \r\n	                  </a>\r\n	                </li>\r\n	\r\n	                <li>\r\n	                  <a href=\"RenderConfigurePersonlityDevelopment\">\r\n	                  <i class=\"fa fa-file-text-o\"></i> \r\n	                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" व्यक्तिमत्व विकास आणि जीवन कौशल्य   ");
}else{ 
      out.write(" Personality Development & Life Skills ");
} 
      out.write(" \r\n	                  </a>\r\n	                </li>\r\n              	</ul>\r\n	          </li>\r\n	           \r\n	           <li >\r\n	              <a tabindex=\"-1\" href=\"RenderClassSubject\">\r\n	              <i class=\"fa fa-book\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" माझा वर्ग  ");
}else{ 
      out.write(" My Class ");
} 
      out.write(" \r\n	              </a>\r\n	           </li>\r\n	          </ul>\r\n        	</li>\r\n        	\r\n        	<li class=\"dropdown \" id=\"reportLiID\">\r\n	          <a href=\"#about\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\">\r\n	            <i class=\"fa fa-line-chart\"></i>\r\n	             ");
 if(form.getMedium().equals("mr")){ 
      out.write(" अहवाल  ");
}else{ 
      out.write(" Reports ");
} 
      out.write(" \r\n	             <span class=\"caret\"></span>\r\n	          </a>\r\n	          \r\n	          <ul class=\"dropdown-menu\">   \r\n            \r\n	            <li >\r\n	              <a tabindex=\"-1\" href=\"RenderClassStudents\">\r\n	              <i class=\"fa fa-file-text-o\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" प्रगतीपुस्तक   ");
}else{ 
      out.write(" Report Card ");
} 
      out.write(" \r\n	              </a>\r\n	            </li>\r\n	           \r\n	            <li>\r\n                  <a href=\"RenderReportCardHistory\">\r\n                  <i class=\"fa fa-file-text-o\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" मागील प्रगतिपुस्तके   ");
}else{ 
      out.write(" Report-Card History ");
} 
      out.write(" \r\n                  </a>\r\n                </li> \r\n                \r\n                <li>\r\n                  <a href=\"RenderReportCardReview\">\r\n                  <i class=\"fa fa-file-text-o\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" प्रगतीपुस्तक आढावा/रिव्ह्यू   ");
}else{ 
      out.write(" Report-Card Review ");
} 
      out.write(" \r\n                  </a>\r\n                </li> \r\n                \r\n	           <li class=\"dropdown-submenu\">\r\n	              <a tabindex=\"-1\" href=\"#\">\r\n	              <i class=\"fa fa-file-text-o\"></i> \r\n	              &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" कस्टम रिपोर्ट   ");
}else{ 
      out.write("  Custom Report ");
} 
      out.write("\r\n	              </a>\r\n	              \r\n	           <ul class=\"dropdown-menu\">\r\n                <li>\r\n                  <a href=\"RenderStudentsCustomReport\">\r\n                  <i class=\"fa fa-file-text-o\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" विद्यार्थी  ");
}else{ 
      out.write(" Students ");
} 
      out.write(" \r\n                  </a>\r\n                </li>\r\n\r\n                <li>\r\n                  <a href=\"RenderExamCustomReport\">\r\n                  <i class=\"fa fa-file-text-o\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" परीक्षा   ");
}else{ 
      out.write(" Exams ");
} 
      out.write(" \r\n                  </a>\r\n                </li> \r\n                \r\n                <li>\r\n                  <a href=\"RenderConfigureConsolidatedSheet\">\r\n                  <i class=\"fa fa-file-text-o\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" एकत्रित पत्रके  ");
}else{ 
      out.write(" Consolidated Sheet ");
} 
      out.write(" \r\n                  </a>\r\n                </li>\r\n                \r\n                <li>\r\n                  <a href=\"RenderXthSTDStudentsReport\">\r\n                  <i class=\"fa fa-file-text-o\"></i> \r\n                  &nbsp;&nbsp;");
 if(form.getMedium().equals("mr")){ 
      out.write(" १० वी - इंटर्नल मार्क्स  रिपोर्ट   ");
}else{ 
      out.write(" STD X - Internal Marks Report ");
} 
      out.write(" \r\n                  </a>\r\n                </li>\r\n                \r\n              </ul>\r\n	        </li>\r\n	      </ul>\r\n        </li>\r\n         \r\n       ");
 } 
      out.write(" 	\r\n    \r\n     </ul>\r\n  </div> <!-- /.navbar-collapse -->   \r\n\r\n</div> <!-- /.container --> \r\n\r\n</div> <!-- /.mainbar -->\r\n\r\n</body>\r\n</html>\r\n    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
