/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-30 05:21:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.kovidRMS.daoImpl.*;
import com.kovidRMS.daoInf.*;
import com.kovidRMS.form.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.24.1.jar", Long.valueOf(1722313424386L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/KovidRMS/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SkoolUp/WEB-INF/lib/struts2-core-2.3.24.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1442915484000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.kovidRMS.daoInf");
    _jspx_imports_packages.add("com.kovidRMS.daoImpl");
    _jspx_imports_packages.add("com.kovidRMS.form");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n    \r\n    \r\n     \r\n	\r\n	\r\n<!DOCTYPE html>\r\n<html class=\"no-js\"> \r\n<head>\r\n\r\n	");

		LoginForm form = (LoginForm) session.getAttribute("USER");
	
		ConfigurationDAOInf daoInf = new ConfigurationDAOImpl();
	
		LibraryDAOInf daoInf1 = new LibraryDAOImpl();
		
		HashMap<Integer, String> ExamList = daoInf.retrieveExaminationListForTimeTable(form.getAcademicYearID());
	
		Integer StudentCount =  daoInf1.retriveStudentCount();
		Integer StudentsIssuedBooksCount =  daoInf1.retriveStudentsBooksIssuedCount("issued");
		Integer StudentsBooksDelayedCount =  daoInf1.retriveStudentsBooksDelayedCount();
		
		Integer StaffCount =  daoInf1.retriveStaffCount();
		Integer StaffIssuedBooksCount =  daoInf1.retriveStaffsBooksIssuedCount("issued");
		Integer StaffsBooksDelayedCount =  daoInf1.retriveStaffsBooksDelayedCount();
		
		Integer BookCount =  daoInf1.retriveBookCount();
	 	Integer AvailableBookCount =  daoInf1.retriveBookCountOfStatus("available");
		Integer OnHoldBookCount =  daoInf1.retriveBookCountOfStatus("on-hold");
		Integer IssuedBookCount =  daoInf1.retriveBookCountOfStatus("issued");
		Integer RetiredBookCount =  daoInf1.retriveBookCountOfStatus("withdrawn");
		Integer DamagedBookCount =  daoInf1.retriveBookCountOfStatus("damaged");
		Integer LostBookCount =  daoInf1.retriveBookCountOfStatus("lost");
		Integer MaintenanceBookCount =  daoInf1.retriveBookCountOfStatus("maintenance");
	
      out.write("\r\n	\r\n	<title>");
 if(form.getMedium().equals("mr")){ 
      out.write("डॅशबोर्ड - SkoolUp");
 }else{ 
      out.write("Dashboard - SkoolUp ");
 } 
      out.write("</title>\r\n\r\n <!-- Favicon -->\r\n 	<link rel=\"shortcut icon\" href=\"images/favicon.jpg\">\r\n  <meta charset=\"utf-8\">\r\n  <meta name=\"description\" content=\"\">\r\n  <meta name=\"viewport\" content=\"width=device-width\">\r\n\r\n  <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700\">\r\n  <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Oswald:400,300,700\">\r\n  <link rel=\"stylesheet\" href=\"font-awesome/css/font-awesome.min.css\">\r\n  <link rel=\"stylesheet\" href=\"./js/libs/css/ui-lightness/jquery-ui-1.9.2.custom.min.css\">\r\n  <link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\r\n \r\n\r\n  <!-- Plugin CSS -->\r\n  <link rel=\"stylesheet\" href=\"./js/plugins/morris/morris.css\">\r\n  <link rel=\"stylesheet\" href=\"./js/plugins/icheck/skins/minimal/blue.css\">\r\n  <link rel=\"stylesheet\" href=\"./js/plugins/select2/select2.css\">\r\n  <link rel=\"stylesheet\" href=\"./js/plugins/fullcalendar/fullcalendar.css\">\r\n\r\n  <!-- App CSS -->\r\n  <link rel=\"stylesheet\" href=\"./css/target-admin.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/custom.css\">\r\n\r\n  <script type=\"text/javascript\" src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\">\r\n</script>\r\n\r\n  <script type=\"text/javascript\">\r\n  $(document).ready(function(){\r\n		$('#dashboardLiID').addClass(\"active\");\r\n		//alert(\"hiii\");	\r\n	});\r\n  \r\n  jQuery(document).ready(function($) {\r\n        $(\".scroll\").click(function(event){     \r\n            event.preventDefault();\r\n            $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n        });\r\n    });\r\n</script>\r\n\r\n<style type=\"text/css\">\r\n    .fixed-header{\r\n        position: fixed;\r\n        top: 43px;\r\n        z-index:1;\r\n        width: 100%;\r\n       	height: 107px;\r\n    }\r\n    .fixed-navbar{\r\n        position: fixed;\r\n        \r\n        width: 100%;\r\n    }\r\n</style>\r\n\r\n<script type=\"text/javascript\">\r\n    $(window).scroll(function(){\r\n	    if ($(window).scrollTop() > 500) {\r\n	        $('#fixedDiv').slideDown(10000);\r\n	        $('#fixedNav').slideDown(10000);\r\n	       $('#fixedDiv').addClass('fixed-header');\r\n");
      out.write("	       $('#fixedNav').addClass('fixed-navbar');\r\n	    }\r\n	    else {\r\n	       $('#fixedDiv').removeClass('fixed-header');\r\n	       $('#fixedNav').removeClass('fixed-navbar');\r\n	    }\r\n	});\r\n    \r\n</script>\r\n\r\n<script type=\"text/javascript\">	var xmlhttp;\r\n		if (window.XMLHttpRequest) {\r\n			xmlhttp = new XMLHttpRequest();\r\n		} else {\r\n			xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n		}\r\n\r\n		function DelayedStudents() {\r\n			\r\n			xmlhttp.onreadystatechange = function() {\r\n				if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\r\n					\r\n					var array = JSON.parse(xmlhttp.responseText);\r\n					\r\n					var check=0;\r\n					var studentName;\r\n					var bookName;\r\n					var expectedReturnDate;\r\n					\r\n					var trTag = \"\";\r\n					\r\n					trTag += \"<tr><td style='text-align:center;'>Student Name</td><td style='text-align:center;'>Book Name</td><td style='text-align:center;'>Expected Return Date</td></tr>\"\r\n					\r\n					for ( var i = 0; i < array.Release.length; i++) {\r\n\r\n						check = array.Release[i].check;\r\n						studentName = array.Release[i].studentName\r\n");
      out.write("						bookName = array.Release[i].bookName; \r\n						expectedReturnDate = array.Release[i].expectedReturnDate;\r\n						\r\n						trTag += \"<tr><td style='text-align:center;'>\"+studentName+\"</td>\"\r\n						  + \"<td style='text-align:center;'>\"+bookName+\"</td>\"\r\n						  + \"<td style='text-align:center;'>\"+expectedReturnDate+\"</td></tr>\";\r\n					}\r\n					\r\n					if(check == 0){\r\n						\r\n						alert(\"There is no delayed student found.\");\r\n						\r\n					}else{\r\n						\r\n						$(\"#tableTRID\").html(trTag);\r\n						$(\"#myModal\").modal(\"show\");\r\n					}\r\n				}\r\n			};\r\n			xmlhttp.open(\"GET\", \"RetrieveDelayedStudents\", true);\r\n			xmlhttp.setRequestHeader(\"Content-type\", \"charset=UTF-8\");\r\n			xmlhttp.send();\r\n		}\r\n	\r\n</script>\r\n\r\n<script type=\"text/javascript\">	var xmlhttp;\r\n		if (window.XMLHttpRequest) {\r\n			xmlhttp = new XMLHttpRequest();\r\n		} else {\r\n			xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n		}\r\n\r\n		function DelayedStaffs() {\r\n			\r\n			xmlhttp.onreadystatechange = function() {\r\n				if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {\r\n");
      out.write("					\r\n					var array = JSON.parse(xmlhttp.responseText);\r\n					\r\n					var check=0;\r\n					var staffName;\r\n					var bookName;\r\n					var expectedReturnDate;\r\n					\r\n					var trTag = \"\";\r\n					\r\n					for ( var i = 0; i < array.Release.length; i++) {\r\n\r\n						check = array.Release[i].check;\r\n						staffName = array.Release[i].staffName\r\n						bookName = array.Release[i].bookName; \r\n						expectedReturnDate = array.Release[i].expectedReturnDate;\r\n						\r\n						trTag += \"<tr><td style='text-align:center;'>Staff Name</td><td style='text-align:center;'>Book Name</td><td style='text-align:center;'>Expected Return Date</td></tr>\"\r\n							  + \"<tr><td style='text-align:center;'>\"+staffName+\"</td>\"\r\n							  + \"<td style='text-align:center;'>\"+bookName+\"</td>\"\r\n							  + \"<td style='text-align:center;'>\"+expectedReturnDate+\"</td></tr>\";\r\n					}\r\n						  \r\n					if(check == 0){\r\n						\r\n						alert(\"There is no delayed staffs found.\");\r\n						\r\n					}else{\r\n						\r\n						$(\"#tableTRID1\").html(trTag);\r\n						$(\"#myModal1\").modal(\"show\");\r\n");
      out.write("					}\r\n				}\r\n			};\r\n			xmlhttp.open(\"GET\", \"RetrieveDelayedStaffs\", true);\r\n			xmlhttp.setRequestHeader(\"Content-type\", \"charset=UTF-8\");\r\n			xmlhttp.send();\r\n		}\r\n	\r\n</script>\r\n\r\n</head>\r\n\r\n<body>\r\n<!-- icluding top menu bar -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topMenu.jsp", out, false);
      out.write("\r\n\r\n<div id=\"myModal\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n	<div class=\"modal-dialog modal-md\">\r\n		<div class=\"modal-content\">\r\n			<div class=\"modal-header\" align=\"center\">\r\n				<b>Student List</b>				\r\n			</div>\r\n			<div class=\"modal-body\">\r\n				<table border=\"1\" id=\"tableTRID\" align=\"center\" class=\"table table-striped table-bordered table-hover table-highlight table-checkable\" data-provide=\"datatable\" \r\n					data-display-rows=\"10\" data-info=\"true\" data-search=\"true\" data-length-change=\"true\" data-paginate=\"true\" style=\"font-size: 14px;\">\r\n					\r\n				</table>\r\n			</div>\r\n			<div class=\"modal-footer\" >\r\n				<button type=\"button\" data-dismiss=\"modal\" align=\"center\">Close</button>\r\n			</div>\r\n		</div>\r\n	</div>\r\n</div>\r\n\r\n<div id=\"myModal1\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\">\r\n	<div class=\"modal-dialog modal-md\">\r\n		<div class=\"modal-content\">\r\n			<div class=\"modal-header\" align=\"center\">\r\n				<b>Staff List</b>			\r\n			</div>\r\n			<div class=\"modal-body\">\r\n				<table border=\"1\" id=\"tableTRID1\" align=\"center\">\r\n");
      out.write("				\r\n				</table>\r\n			</div>\r\n			<div class=\"modal-footer\">\r\n				<button type=\"button\" data-dismiss=\"modal\" style=\"text-align: center;\">Close</button>\r\n			</div>\r\n		</div>\r\n	</div>\r\n</div>\r\n\r\n<div class=\"container\">\r\n\r\n  <div class=\"content\">\r\n\r\n    <div class=\"content-container\" style=\"z-index: 0;\">\r\n     \r\n	<div class=\"form-group\">\r\n	 <div id=\"google_translate_element\" style=\"display:none\"></div> \r\n		<div>\r\n			");
  
				for(Integer ExamFormName : ExamList.keySet()){
			
      out.write("\r\n				<h1>");
      out.print(ExamList.get(ExamFormName));
      out.write("</h1>\r\n				<div style=\"widows: 20px;text-align: center;\"><b>Time Table For Primary</b></div>\r\n				<div class=\"row\">\r\n					<table id=\"datatable-responsive\" class=\"table table-striped table-bordered dt-responsive nowrap\" cellspacing=\"0\" width=\"100%\">\r\n						\r\n						<tr>\r\n							<td style=\"widows: 20px;text-align: center;\">Date</td>\r\n							\r\n							");
 String finalStandardList =  daoInf.retriveStandarNameByStage("Primary",ExamFormName);
						
							String[] TimeTableDetails = finalStandardList.split(",");
	                       	
				            for (int i = 0; i < TimeTableDetails.length; i++) 
							{ 
				        		
      out.write("\r\n						          <td style=\"widows: 20px;text-align: center;\">");
      out.print(TimeTableDetails[i].trim());
      out.write("</td>\r\n				                ");

					        }
      out.write("\r\n						</tr>\r\n						\r\n						");
 List<String> DateList = daoInf.retrieveDateList(ExamFormName);
							//System.out.println("DateList: "+DateList);
							for(String DateFormName : DateList){ 
      out.write("\r\n							\r\n							<tr>\r\n								<td style=\"widows: 20px;text-align: center;\">");
      out.print(DateFormName);
      out.write("</td>\r\n								\r\n								");
 List<Integer>StandardIDList = daoInf.retrieveStandardIDList("Primary", ExamFormName, DateFormName);
									
									for(Integer StandardIDName : StandardIDList){
										
										List<String> SubjectList = daoInf.retrieveSubjectList(ExamFormName, DateFormName,StandardIDName);
										
										for(String SubjectFormName : SubjectList){
      out.write("\r\n										\r\n											<td style=\"widows: 20px;text-align: center;\">");
      out.print(SubjectFormName);
      out.write("</td>\r\n											\r\n										");
 }
									}
								
      out.write("\r\n							</tr>\r\n							\r\n							\r\n						");
 } 
      out.write(" \r\n					</table>\r\n				</div>\r\n				\r\n				<hr>\r\n				\r\n				<div class=\"row\">\r\n				<div style=\"widows: 20px;text-align: center;\"><b>Time Table For Secondary</b></div>\r\n					<table id=\"datatable-responsive\" class=\"table table-striped table-bordered dt-responsive nowrap\" cellspacing=\"0\" width=\"100%\">\r\n						<tr>\r\n							<td style=\"widows: 20px;text-align: center;\">Date</td>\r\n							\r\n							");
 String finalStandardList1 =  daoInf.retriveStandarNameByStage("Secondary", ExamFormName);
						
								String[] TimeTableDetails1 = finalStandardList1.split(",");
		                       	
					            for (int i = 0; i < TimeTableDetails1.length; i++) 
								{ 
					        		
      out.write("\r\n							          <td style=\"widows: 20px;text-align: center;\">");
      out.print(TimeTableDetails1[i].trim());
      out.write("</td>\r\n					                ");

						        }
      out.write("\r\n						</tr>\r\n						");
 List<String> DateList1 = daoInf.retrieveDateList1(ExamFormName);
							//System.out.println("DateList: "+DateList);
							for(String DateFormName1 : DateList1){
      out.write("\r\n							\r\n							<tr>\r\n								<td style=\"widows: 20px;text-align: center;\">");
      out.print(DateFormName1);
      out.write("</td>\r\n								\r\n								");
 List<Integer>StandardIDList = daoInf.retrieveStandardIDList("Secondary", ExamFormName, DateFormName1);
									
									for(Integer StandardIDName : StandardIDList){
										
										List<String> SubjectList = daoInf.retrieveSubjectList(ExamFormName, DateFormName1,StandardIDName);
										
										for(String SubjectFormName : SubjectList){
      out.write("\r\n										\r\n											<td style=\"widows: 20px;text-align: center;\">");
      out.print(SubjectFormName);
      out.write("</td>\r\n											\r\n										");
 }
									}
								
      out.write("\r\n							</tr>\r\n							\r\n						");
 } 
      out.write(" \r\n					</table>	\r\n				</div>\r\n			");

				}
			
      out.write("\r\n		</div>\r\n	\r\n	</div>\r\n	\r\n	");
 if(form.getRole().equals("librarian")){ 
      out.write("\r\n		<div class=\"form-group\">\r\n			 <div>\r\n				 <div style=\"font-size: 25px;widows: 20px;text-align: center;padding-bottom: 20px;\"><b>Students</b></div>\r\n				\r\n				<div class=\"row\">\r\n					<div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\">Total Student Count</p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(StudentCount );
      out.write("</h3>\r\n			          </div>\r\n			        </div> \r\n			\r\n					<div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\"><a href=\"RenderconfigureStudentIssue\">Books Issued Count</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(StudentsIssuedBooksCount );
      out.write("</h3>\r\n			          </div> \r\n			        </div> \r\n			        \r\n			        <div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\"><a href=\"javascript:DelayedStudents();\">Books Delayed Count</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print( StudentsBooksDelayedCount);
      out.write("</h3>\r\n			          </div>\r\n			        </div>\r\n	        	</div>\r\n				\r\n			<hr>\r\n						\r\n				<div style=\"font-size: 25px;widows: 20px;text-align: center;padding-bottom: 20px;\"><b>Staff</b></div>\r\n				\r\n				<div class=\"row\">\r\n					<div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\">Total Staff Count</p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(StaffCount );
      out.write("</h3>\r\n			          </div>\r\n			        </div> \r\n			\r\n					<div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\"><a href=\"RenderconfigureStaffIssue\">Books Issued Count</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(StaffIssuedBooksCount );
      out.write("</h3>\r\n			          </div> \r\n			        </div> \r\n			        \r\n			       <div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\"><a href=\"javascript:DelayedStaffs();\">Books Delayed Count</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(StaffsBooksDelayedCount );
      out.write("</h3>\r\n			          </div>\r\n			        </div>\r\n	        	</div>\r\n	        \r\n			<hr>	\r\n				\r\n				<div style=\"font-size: 25px;widows: 20px;text-align: center;padding-bottom: 20px;\"><b>Inventory</b></div>\r\n				\r\n				<div class=\"row\">\r\n					<div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\">Total Books</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(BookCount );
      out.write("</h3>\r\n			           \r\n			          </div>\r\n			        </div> \r\n			\r\n					<div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\">Available Books</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(AvailableBookCount );
      out.write("</h3>\r\n			           </div> \r\n			        </div> \r\n			        \r\n			       <div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\">On-hold Books</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(OnHoldBookCount );
      out.write("</h3>\r\n			          </div>\r\n			        </div>\r\n	        	</div>\r\n	        	\r\n	        	<div class=\"row\">\r\n					<div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\">Issued Books</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(IssuedBookCount );
      out.write("</h3>\r\n			          </div>\r\n			        </div> \r\n			\r\n					<div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\">Retired Books</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(RetiredBookCount );
      out.write("</h3>\r\n			          </div> \r\n			        </div> \r\n			        \r\n			       <div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\">Damaged Books</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(DamagedBookCount );
      out.write("</h3>\r\n			          </div>\r\n			        </div>\r\n	        	</div>\r\n	        	\r\n	        	<div class=\"row\">\r\n					<div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\">Lost Books</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(LostBookCount );
      out.write("</h3>\r\n			           </div>\r\n			        </div> \r\n			\r\n					<div class=\"col-sm-6 col-md-4\" align=\"center\">\r\n			          <div class=\"row-stat\" style=\"width: 50%;\">\r\n			            <p class=\"row-stat-label\">Maintenance Books</a></p>\r\n			            <h3 class=\"row-stat-value\">");
      out.print(MaintenanceBookCount );
      out.write("</h3>\r\n			           </div>\r\n			        </div>\r\n	        	</div>\r\n				\r\n			</div>\r\n		</div>\r\n	\r\n	");
 } 
      out.write("\r\n\r\n    </div> <!-- /.content-container -->\r\n      \r\n  </div> <!-- /.content -->\r\n\r\n</div> <!-- /.container -->\r\n\r\n  ");
      out.write("\r\n  <script src=\"./js/libs/jquery-ui-1.9.2.custom.min.js\"></script>\r\n  <script src=\"./js/libs/bootstrap.min.js\"></script>\r\n\r\n  <!--[if lt IE 9]>\r\n  <script src=\"./js/libs/excanvas.compiled.js\"></script>\r\n  <![endif]-->\r\n  \r\n  <!-- Plugin JS -->\r\n  <script src=\"./js/plugins/icheck/jquery.icheck.js\"></script>\r\n  <script src=\"./js/plugins/select2/select2.js\"></script>\r\n  <script src=\"./js/libs/raphael-2.1.2.min.js\"></script>\r\n  <script src=\"./js/plugins/morris/morris.min.js\"></script>\r\n  <script src=\"./js/plugins/sparkline/jquery.sparkline.min.js\"></script>\r\n  <script src=\"./js/plugins/nicescroll/jquery.nicescroll.min.js\"></script>\r\n  <script src=\"./js/plugins/fullcalendar/fullcalendar.min.js\"></script>\r\n\r\n  <!-- App JS -->\r\n  <script src=\"./js/target-admin.js\"></script>\r\n  \r\n  <!-- Plugin JS -->\r\n  <script src=\"./js/demos/dashboard.js\"></script>\r\n  <script src=\"./js/demos/calendar.js\"></script>\r\n  <script src=\"./js/demos/charts/morris/area.js\"></script>\r\n  <script src=\"./js/demos/charts/morris/donut.js\"></script>\r\n");
      out.write("\r\n  \r\n</body>\r\n</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
